### ISSUE TITLE
"Change Airspeed" Button with ArduPlane/no airspeed sensor

### ISSUE THREAD

**Issue by jacobsenmd** [diydrones/MissionPlanner#1001]
Recommend automatically changing the "Change Airspeed" button label to "Change Throttle" when using ArduPlane with ARSPD_ENABLE set to 0. In this mode the plane flies in AUTO based on target throttle settings, not airspeeds. The window displays TRIM_THROTTLE under these circumstances, so the button should be re-labeled to more accurately convey what is going on.

How ArduPlane flies without an airspeed sensor has traditionally been a subject of confusion for newer users.

**Comment by meee1** [comment]
makes sence

**Comment by meee1** [comment]
done
