### ISSUE TITLE
Bug: Create KML when in DGPS

### ISSUE THREAD

**Issue by RoverHunter** [diydrones/MissionPlanner#1003]
When in DGPS mode, the "Create KML + gpx" tool is unable to create the path. However the logfile is correct correctly. When using "Review a Log" I can see the entire mission, even under GPS/Status I can see the entire mission: 1(NO_FIX), then 3 (GPS_OK_FIX_3D) and finally 4 (GPS_OK_FIX_3D_DGPS), however when in this last mode, no path on the kmz file.

**Comment by meee1** [comment]
fixed in the current beta MP.

**Comment by meee1** [comment]
mp 1.3.32 fixs this
