### ISSUE TITLE
Different Change Log links in different parts of Mission Planner

### ISSUE THREAD

**Issue by airborneimager** [diydrones/MissionPlanner#1005]
I just noticed with the latest release of MP (1.3.32) that the two locations from which one can access the Change Log in Mission Planner actually link to different versions of the change log, one of which is months out of date.

If one clicks the Change Log link at the bottom of the Help screen, one is taken to this file, which hasn't been updated for three months:
http://firmware.diydrones.com/Tools/MissionPlanner/upgrade/ChangeLog.txt

The other link, which is in the dialog box that pops up when a new (beta) version is available, links here (has been updated as of today, 2015-09-15):
http://firmware.diydrones.com/MissionPlanner/upgrade//ChangeLog.txt

I don't know if this is by design, but it seems to me that a full version release should be accompanied by an up-to-date change log. It also seems odd that there are two root paths, one containing /Tools and the other not, that both seem to go to the same file hierarchy.

**Comment by meee1** [comment]
I just checked, and they are the same file, both up to date, so if they are different, it must be some proxy server you are using.
