### ISSUE TITLE
Add ability to ignore SR_0, SR_1, SR_2, SR_3 params

### ISSUE THREAD

**Issue by magicrub** [diydrones/MissionPlanner#1006]
When MP connects it sets some packet rates presumably for UX reasons. This may be overriding SR values set by a companion computer. There should be a checkbox in advanced that, when checked, does not set any of the SR params.

**Comment by magicrub** [comment]
related to https://github.com/diydrones/MissionPlanner/issues/1004

**Comment by meee1** [comment]
with the talk on #1004 i dont think this is valid anymore.
