### ISSUE TITLE
Latest Beta defaults Telemetry rates to 0

### ISSUE THREAD

**Issue by Jman841** [diydrones/MissionPlanner#1011]
Not sure why, but, with the latest beta release, the telemetry rates for planner are all Zeroed out. I changed them to a higher value, but, when I connected to a pixhawk they defaulted to 0 again.

**Comment by mike-dslrpros** [comment]
I have the same problem here.

**Comment by meee1** [comment]
new beta uploaded that should resolve. thanks for the heads up.
