### ISSUE TITLE
New RSSI parameters in ArduPlane 3.4.0 have no help

### ISSUE THREAD

**Issue by StewLG** [diydrones/MissionPlanner#1015]
The new RSSI parameters in ArduPlane 3.4.0 have no help in Mission Planner - I tried release and beta, specifically Mission Planner 1.1.5745.29653.

![rssiparametersnotfound](https://cloud.githubusercontent.com/assets/7128339/10092589/fc73b3e0-62fc-11e5-8ea0-7185db818d86.png)

If I'm missing something about the way releases work please set me straight.

**Comment by meee1** [comment]
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_RSSI/AP_RSSI.cpp
has malformed param names in it.
"RSSI_" is gathered from the main paramerter.cpp, however in the linked file it also has RSSI_*.
so either the main parameter.cpp needs to be changed to "" or the linked file needs to remove the "RSSI_"

**Comment by meee1** [comment]
eg http://plane.ardupilot.com/wiki/arduplane-parameters/#rssi__parameters

**Comment by StewLG** [comment]
This has now been fixed in trunk. Thanks for the explanation.
