### ISSUE TITLE
Easy search for Full Parameter List

### ISSUE THREAD

**Issue by GrahamDyer** [diydrones/MissionPlanner#1020]
It would be very convenient to have a persistent search box in the right hand side-bar which populated as soon as anything was typed after loading, rather than having to click "Find" or CTRL-F (which first brings up the temp screen) and then typing.

This wouldn't interfere which parameter editing as it could/would lose focus as soon as any parameter was clicked. 

With so many parameters, unless one knows the name exactly in which case one can scroll to it, the way to find something is to search and this would just make it that much easier and faster.

**Comment by iskess** [comment]
+1, this would be a huge help!

It would be really nice to have a custom parameter page where we could arrange our own list of frequently used parameters. Or the ability to hide parameters that we will never look at, along with a "show all" button to reveal all hidden items. 
As the parameter list continues to grow, it is slowing down the workflow in the field.

**Comment by GrahamDyer** [comment]
Works very, very well on the beta, impressive, thank you! 
Another small suggestion: it could have a small "clear" button to clear the box of text to go quickly back to the full list.

**Comment by GrahamDyer** [comment]
Works amazingly well, thank you Michael!

**Comment by meee1** [comment]
good to hear

**Comment by GrahamDyer** [comment]
Best addition ever :)
