### ISSUE TITLE
no georeference possible

### ISSUE THREAD

**Issue by Basti77** [diydrones/MissionPlanner#1026]
The georeference of the images dont work in in the current Mission Planner version.

i meen the hidden Controll+f Option.

The bin file is converted to the log Format, but it is no position data stored in relation to the camera trigger.

in earlier versions, this has worked.

**Comment by meee1** [comment]
please provide a log, so I can check against

**Comment by Basti77** [comment]
Hello Michael.

http://www.droneshare.com/mission/152575

Where should I upload the Bin File? Zip files are not accepted here.

Greeting Sebastian

**Comment by Basti77** [comment]
I've found the problem.
in the georeferencing tool is missing the console.
You get no feedback for debugging.

My problem was, the camera has 2 more images recorded as than planned.

Would it be possible to install the console back in the current version?

**Comment by meee1** [comment]
to get the console, just goto help an tick the console box.

**Comment by Basti77** [comment]
I mean this area with debug console.
![geo ref 01](https://cloud.githubusercontent.com/assets/8112783/10424479/c434022e-70cf-11e5-8c44-a4f07314bc7e.PNG)
![georef02](https://cloud.githubusercontent.com/assets/8112783/10424480/c436112c-70cf-11e5-8713-1af368f2cb7d.PNG)
