### ISSUE TITLE
Auto analysis, GPX creation and upload to Droneshare not working

### ISSUE THREAD

**Issue by GrahamDyer** [diydrones/MissionPlanner#1036]
Currently any of the logs created by Copter v3.3 on my tricopter do not work or fail in the following errors:

Auto analysis fails with:
![aa1](https://cloud.githubusercontent.com/assets/3287001/10546625/66ed7092-742f-11e5-94b8-7e0ebd523f3e.JPG)
and:
![aa2](https://cloud.githubusercontent.com/assets/3287001/10546633/757e7e94-742f-11e5-932e-b8e4d3ead248.JPG).

GPX creation works but the file has an error:
![gpx1](https://cloud.githubusercontent.com/assets/3287001/10546686/cb1c73f6-742f-11e5-9315-997b7c7c1720.JPG)

Upload to Droneshare fails with:
![ds](https://cloud.githubusercontent.com/assets/3287001/10546749/2946bb80-7430-11e5-9f5a-7b5353ec0e17.JPG)

**Comment by foobarbecue** [comment]
n.b. I get "invalid location" from apmplanner2 as well. Droneshare server side is not open source so pff

**Comment by meee1** [comment]
could you upload the gpx that was created? just so I can see whats invalid in it?

**Comment by GrahamDyer** [comment]
Delete the ".gif" of the filename
![2015-10-16 17-26-54 log gpx.gif](https://cloud.githubusercontent.com/assets/3287001/10628645/ca2bb52e-77c7-11e5-82e5-1079f45201b4.gif)

**Comment by meee1** [comment]
I cant see anything wrong with the gpx file

**Comment by GrahamDyer** [comment]
Went an tried it on a different viewer and it works fine, don't know why Garmin Basecamp reports an unknown error on that file.

**Comment by meee1** [comment]
closing
