### ISSUE TITLE
Add RPM Message Display in Tuning Window

### ISSUE THREAD

**Issue by R-Lefebvre** [diydrones/MissionPlanner#1038]
Please add RPM message in the tuning window.  Details on new Mavlink message contained here:

https://github.com/diydrones/ardupilot/commit/8f1e1a1b4aaed5b64d8e64602eeb94f7be190610

**Comment by meee1** [comment]
done

**Comment by R-Lefebvre** [comment]
Great, thanks. I assume if I go to the beta version, I'll see it?

**Comment by meee1** [comment]
yep
