### ISSUE TITLE
Unable to open a particular Copter-3.3.1-rc1 dataflash log

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#1040]
I get the following message when I try to open this dataflash .bin file.
![mperror](https://cloud.githubusercontent.com/assets/1498098/10625781/71f6353a-77e2-11e5-9bf9-da423e7768f8.png)

https://dl.dropboxusercontent.com/u/3852647/MichaelO/Copter331-cannot-open.bin

Strangely I can convert the .bin to .log and then open it.

**Comment by meee1** [comment]
there must be a new DF type of 255.

fixed
https://github.com/diydrones/MissionPlanner/commit/ba4a296f2153f19a6a5c6f155d2cf2f3a49de6b1
