### ISSUE TITLE
MP reads out Pixhawk Serial Number on making Mavlink connection to AC3.3

### ISSUE THREAD

**Issue by R-Lefebvre** [diydrones/MissionPlanner#1043]
Something to do with changed message severities?  Sorry, I don't have more info, I'm paraphrasing from Randy.

**Comment by R-Lefebvre** [comment]
Related to this:

https://github.com/diydrones/MissionPlanner/issues/977

**Comment by rmackay9** [comment]
My guess is that mission planner isn't using the ardupilot version to separate the new or old style severities should be used.  I think perhaps what's happened is that the new style severities are used for Copter-3.3.

**Comment by meee1** [comment]
this should now be resolved. in current beta MP
