### ISSUE TITLE
Improvement Request: Insert messages in the 'Messages tab, instead of append

### ISSUE THREAD

**Issue by ggregory8** [diydrones/MissionPlanner#1046]
Hi, can we change the order of the messages in the 'Messages' tab so new messages are inserted at the top, instead of appending to the end.
When more messages are received, than what fits in the display, you cannot see the messages. If you scroll to the bottom it will always reset the scrollbar to the top when a new message is received.

**Comment by meee1** [comment]
done

**Comment by ggregory8** [comment]
Great thanks!
