### ISSUE TITLE
Disable drag and drop for markers

### ISSUE THREAD

**Issue by kjeremy** [diydrones/MissionPlanner#1058]
In my plugin I have custom markers added through an overlay and I do not want the user to move them (they represent fixed geo locations).  Currently I add them to the flight planner and the user can drag and drop them but I want to disable the drag and drop.  I'm looking for a GMapMarker.DisableDrag or something like that but don't see anything that would disable the action.

**Comment by meee1** [comment]
https://github.com/diydrones/MissionPlanner/pull/1066
