### ISSUE TITLE
Exception when trying to save WP file

### ISSUE THREAD

**Issue by DroneBuster** [diydrones/MissionPlanner#1059]
Hi,
I found problem with saving wp to file. I appears that filter provided for save dialog is incorrect. I have already fixed problem here: https://github.com/DroneBuster/MissionPlanner/tree/save_wp_fix
But this makes loading of .waypoint files impossible thus load wp filter must be changed
https://github.com/diydrones/MissionPlanner/blob/master/GCSViews/FlightPlanner.cs#L2511
What files should be left here? I'm thinking that .waypoint should be enough?

Then this will be sorted I could create pull request.

**Comment by DroneBuster** [comment]
I see you already have fixed it. ba9b629

**Comment by meee1** [comment]
yep, thanks for the info though
