### ISSUE TITLE
Hidden screen is not displaying with mono (mac and linux)

### ISSUE THREAD

**Issue by kikislater** [diydrones/MissionPlanner#1063]
Hi,

I run Mission Planner under Mac and Linux but unfortunately the hidden screen (CTRL + F) is not working.
Shall it be possible to integrate a button in the GUI instead of hiting keyboard shortcut ?

Thanks 

Sylvain

**Comment by meee1** [comment]
in the next beta/release there will be a testing screen checkbox in the planner config page that will open the screen.
