### ISSUE TITLE
AltWarn and absolute Alt

### ISSUE THREAD

**Issue by arnaudstephan** [diydrones/MissionPlanner#1069]
Hi !

using Mission planner 1.3.32 building 1.1.573630798

After creating a survey, when you enter an altwarn under 0 (for ex : -100) and when you save the WP file, the WP file is written with the code 0 in the third column in the .txt file (see file attached). After that, when you click write PNs button, missionplanner indicates : "Absolute alt is selected, are you sure ?" Usually, i click "N"o to be sure the relative alt is used in the automission.

I change the altwarn in some missions beacause sometimes, my uav nedd to follow the relief and some points of the automission are under the take of altitude.

Afterthat, it is impossible to geotag photos with the "USE AMSL alt" box checked. The photos can be geottaged only with relative alt. I checked the log file from mavlink and there is the absolute and relative alt written in.

Thank you.
[carreauHO.txt](https://github.com/diydrones/MissionPlanner/files/43631/carreauHO.txt)

**Comment by meee1** [comment]
there was a bug in the amsl alt option, please try beta MP
help > update beta.
