### ISSUE TITLE
Survey grid screen

### ISSUE THREAD

**Issue by jcooper21** [diydrones/MissionPlanner#1071]
It would be nice if the survey grid screen was able to be seen after the mission is planned and accepted for reference purposes. It could be as simple as a button on the right side of the mission planning screen under the write data button.

**Comment by kikislater** [comment]
+1
And also export it to kml/shape

**Comment by meee1** [comment]
what is the intent behind this request. just trying to understand the reason, and to see if there are better alternatives.

**Comment by iskess** [comment]
I believe the intent is to be able to save and edit a survey grid. If for example you want to make a small change after hitting Accept. Or if you want to fly the same grid as last week, but change the camera.

**Comment by meee1** [comment]
try control-s and control-o
s to save
o to load

while in the grid screen

**Comment by iskess** [comment]
That works!
Thanks. 

Iam

**Comment by meee1** [comment]
I'm going to close this, as ive partially answered ad have received no further response
