### ISSUE TITLE
DF Bin -> Log then Reviewing that .log causes null exception

### ISSUE THREAD

**Issue by magicrub** [diydrones/MissionPlanner#1075]
v1.3.33 build 1.1.5820.11240 regression.

"Review a Log" using any .bin works
"Review a Log" using a .log generated from <=v1.3.32 works
Pressing "PX4 .Bin to .Log" and then reviewing that .log causes a nullExcepion

Reports are that it is broken on Rover and Plane but works for Copter logs.

**Comment by meee1** [comment]
tom, I have tested all the firmwares, and cant replicate this issue.

**Comment by meee1** [comment]
can you provide the specific log

**Comment by magicrub** [comment]
I just tried it on another new log from master and it worked on v1.3.33 but
still fails on this log from master a month ago
https://drive.google.com/open?id=0B6RPB3yIS_0MRGNhMzVqbklmLWM

**Comment by magicrub** [comment]
That is, ardupilot master

**Comment by meee1** [comment]
the issue is this

MSG, Demo Servos!
MSG, Demo Servos!
MSG, Initialising APM...
MSG, Demo Servos!
MSG, 

 Ready to FLY.
STRT, 7, 41

there are extra line feeds for some reason.

**Comment by meee1** [comment]
this should be resolved.
