### ISSUE TITLE
Adding a new Flightmode(Plane)

### ISSUE THREAD

**Issue by Leomessi1000** [diydrones/MissionPlanner#1076]
I tried to add a new Flightmode. I implement the MissonPlanner.  (I use ArduPlane V2.74b)
It's explained on http://dev.ardupilot.com/wiki/apmcopter-adding-a-new-flight-mode/
However,this page explained only a copter code. I would like to know how to add a new Flightmode about a Plane.
 Has anyone got an idea?

**Comment by meee1** [comment]
please post this question on the ardupilot list.
