### ISSUE TITLE
Elevation profile Graph crashes

### ISSUE THREAD

**Issue by jmachuca77** [diydrones/MissionPlanner#1084]
When trying to display the elevation graph I get a crash with the following error:
<img width="560" alt="screen shot 2015-12-14 at 10 03 13 pm" src="https://cloud.githubusercontent.com/assets/1664405/11801805/f554044c-a2ae-11e5-9fa8-8ce91c2d4a23.png">

**Comment by meee1** [comment]
I think its something specific in your mission that's causing this. but ive added a null check anyway.

**Comment by jmachuca77** [comment]
I have tried on several missions and I get the same result. all the missions were done with the survey grid . I'll upload my mission if it helps.

**Comment by jmachuca77** [comment]
This is the mission:

[elevationgraphcrash.waypoints.txt](https://github.com/diydrones/MissionPlanner/files/63281/elevationgraphcrash.waypoints.txt)

**Comment by meee1** [comment]
thanks for the wp file, that shoed me the issue. next beta will be fixed.
