### ISSUE TITLE
Throwing an error in UI when selecting "Camera Gimbal" in Optional Hardware config

### ISSUE THREAD

**Issue by travmason** [diydrones/MissionPlanner#1085]
In the UI when I'm selecting the Camera Gimbal config in the Initial Config/Optional Hardware menu it is throwing the attached error.

MP 1.3.33

Also might add a new issue to be able to select the text from that error window...

![capture](https://cloud.githubusercontent.com/assets/1578379/11858179/4248860a-a4b3-11e5-83c2-11f36f772f51.PNG)

**Comment by meee1** [comment]
thanks, fixed

**Comment by travmason** [comment]
Champion, will test in field today.

**Comment by meee1** [comment]
you will need to download the beta mp to see that change

**Comment by travmason** [comment]
I was going to have a crack at compiling it myself ;-)

**Comment by travmason** [comment]
Harder than I thought it would be to find the beta downloads...where are
they hiding??

--
Travis Mason
travis.mason@gmail.com

**Comment by meee1** [comment]
goto help > update beta

**Comment by travmason** [comment]
Duh. Thanks!

--
Travis
