### ISSUE TITLE
Bin file conversion Planes modes determined instead of Copter?

### ISSUE THREAD

**Issue by bionicbone** [diydrones/MissionPlanner#1089]
I have a log from APM:Copter, but in Mission Planner it states mode FBWB (plane mode) was used?

If I run the the Bin to Log conversion I get:
MODE, 178180900, FBWB, 6 on line 19585, other modes are Plane mode also like Normal.

Mission Planner 1.3.33 Build 1.1.5820.11240
APM:Copter V3.3.2 (7f16e4d6)

Is this a conversion issue or something else?
 
[10 - Mission Planner.zip](https://github.com/diydrones/MissionPlanner/files/67751/10.-.Mission.Planner.zip)

**Comment by meee1** [comment]
ive updated the detection rule, but in this case it would be processed as whatever you where last connected to.
