### ISSUE TITLE
Display servo outputs for channel 9 ~ 16

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#1090]
Rob wanted to merge in this change to copter:
https://github.com/R-Lefebvre/ardupilot/commit/5cf703fbddd1c68593a70f1f357e09ff4cba2546

but during testing we found that mission planner seems to overwrite the ch1out, ch2out, etc with the values from channel 9~16.  Perhaps it's not checking the "port" parameter of the servo-output-raw message?

http://mavlink.org/messages/common#SERVO_OUTPUT_RAW

**Comment by R-Lefebvre** [comment]
This is related to this Issue:

https://github.com/diydrones/ardupilot/issues/1968

**Comment by meee1** [comment]
fixed

**Comment by R-Lefebvre** [comment]
Is this fixed in the current beta release?  I just tested it, and still not working though I see it is showing servo values for 1-16.
