### ISSUE TITLE
Fail to retrieve logs from PixHawk via USB

### ISSUE THREAD

**Issue by lvale** [diydrones/MissionPlanner#1094]
Error occurs when retrieving logs via USB from PixHawk. Beta version on screenshot. Both APM Planner on OS X and MavProxy on Windows can retrieve the exact same logs.
<img width="1206" alt="screen shot 2016-01-04 at 16 41 47" src="https://cloud.githubusercontent.com/assets/3130363/12102852/cec384be-b335-11e5-8d15-154e0173f913.png">

**Comment by meee1** [comment]
thanks for that, I will fix

**Comment by meee1** [comment]
beta should be fixed
