### ISSUE TITLE
Parachute deploy mission item

### ISSUE THREAD

**Issue by squilter** [diydrones/MissionPlanner#1096]
Deploying the parachute is a done with a `MAV_CMD_DO_PARACHUTE` with param1 set to 2.  It would be nice if this were supported as a mission item.

**Comment by meee1** [comment]
does all codebases support this?
plane copter rover? etc?

**Comment by squilter** [comment]
The current version of copter supports it.  The next release of plane will support it.  Rover will not support it.

**Comment by meee1** [comment]
cool, that's what I thought. changes are in.
