### ISSUE TITLE
Antenna tracker

### ISSUE THREAD

**Issue by AnthonyVerloop** [diydrones/MissionPlanner#1104]
Mission Planner seem to write tlogs randomly, when connected to the antenna tracker which is connected to an airplane. My workaround is like this:

Connect Mission planner, and it surely connects to the antenna tracker first, then to the Plane. Select Fixed-Wing, disconnect, wait about 3 seconds, and connect again. 90% sure it connects to the plane first, then to the antenna tracker. Tlog files will now be written under fixed wing and can be replayed in mission planner.

But it's still a bit of a lottery game. Sometimes you just have to disconnect and connect again a few times until MP connects to the Fixed wing first. That way the log files will be written in the fixed wing directory.

I don;t know if this is a MP problem or AT Tracker firmware problem, but it seems to me it is a MP problem.

Is it possible to have a choice? I basically only want to see the Fixed wing logfiles and th tracker logfiles only now and then.

**Comment by meee1** [comment]
mp now trys to use the non AT code.
