### ISSUE TITLE
Waypoint Variables. 

### ISSUE THREAD

**Issue by MusabAlaqeede** [diydrones/MissionPlanner#1111]
I am trying to update the waypoints on the flight plan through a webapplication I have designed, I have managed to connect mission planner to the database on the webapplication and I am able to retrieve the data (Longitude and latitude). however I have failed to find the variables that make the waypoints. I might have been looking in the wrong files to begin with... please help direct me. 

Attached below is an image  how I want the data to appear after updating the database.  
![capture23412](https://cloud.githubusercontent.com/assets/16340776/12530735/35fdcfe4-c223-11e5-80e8-48fcaa05df57.JPG)

**Comment by meee1** [comment]
your question is way too vague.

**Comment by MusabAlaqeede** [comment]
Which part of the question are you unclear on ?

**Comment by meee1** [comment]
look at the function 
public void AddWPToMap(double lat, double lng, int alt)
or
public void setfromMap(double lat, double lng, int alt, double p1 = 0)

**Comment by MusabAlaqeede** [comment]
Thank you so much for your kind response, I am trying to set the 'lat','lng' & 'alt' from a different program as an API, how would I approach this matter as I am new to C#.
