### ISSUE TITLE
Request : Indonesia Translation

### ISSUE THREAD

**Issue by robetyosua** [diydrones/MissionPlanner#1113]
i just finished translate into bahasa indonesia, i hope you can implement this language on mission planner. thank you
[translation.zip](https://github.com/diydrones/MissionPlanner/files/103009/translation.zip)

**Comment by kjeremy** [comment]
@robetyosua Just out of curiosity how did you perform the translation?  Did you use any plugins or other software?  I'm trying to translate to Korean.

**Comment by meee1** [comment]
please see here
http://planner.ardupilot.com/wiki/mission-planner-language-translations/

**Comment by meee1** [comment]
merged thanks
