### ISSUE TITLE
Fails to upload mission to 3DR solo

### ISSUE THREAD

**Issue by leondwyer** [diydrones/MissionPlanner#1119]
System.FormatException: Input string was not in a correct format.

Sorry I would have sumbmitted the error but you don;t have the interwebs when you are using the Solo.
See screen grab

![mp error](https://cloud.githubusercontent.com/assets/985163/12637422/476f266e-c5e9-11e5-8df5-4886493a135a.png)

**Comment by leondwyer** [comment]
This is also happening on my pixhawk mapper whats the fix for this I have uninstalled and reinstalled and I'm still getting this same error, help I have a job and work to do.

**Comment by meee1** [comment]
in your screenshot look in the alt warning box.

change it to 0.
