### ISSUE TITLE
Mission planner 1.3.34 =  Empty fields for flight modes

### ISSUE THREAD

**Issue by JeyPi** [diydrones/MissionPlanner#1121]
I get nothing in the fields for flight modes Configuring/Flight Modes
The fields are empty without any action to be taken.
If I click on the right field arrow no list pops up.
I had to downgrade to have this working

**Comment by meee1** [comment]
in MP press control-F, then click "param gen"
wait for that to complete.
then restart mp

**Comment by JeyPi** [comment]
Thanks it works. Shouldnt it be mentioned somewhere in the manual?

**Comment by meee1** [comment]
normally its not an issue, most likerly a failed update attempt
