### ISSUE TITLE
quick key for switching between quick,actions... tabs

### ISSUE THREAD

**Issue by haogodent2** [diydrones/MissionPlanner#1122]
This is a feature request. It would be nice if the tabs are slaved to different number values. This way we can quickly switch between tabs such as quick and actions which I find myself doing very often.

**Comment by meee1** [comment]
this I think could happen.
what key shortcuts would you suggest?

**Comment by haogodent2** [comment]
I think using the 1,2,3,4,5... number keys would make sense here since there are quite a few sequential tabs and they are not currently mapped to anything.

**Comment by meee1** [comment]
what about the modifier key? ie shift/ctl/ etc.

**Comment by haogodent2** [comment]
I see that that ctrl+tab already scrolls through the different tabs. Do you mean ctrl+1, ctrl+2? That would work for me.

**Comment by meee1** [comment]
that could work,

currently f2-f4 switch the main views
and f12 connects.
so ctrl-1... sounds like a good idea

**Comment by haogodent2** [comment]
Ah, didn't know the F1,F2 shortcut, that's actually pretty cool for switching frequently between flight, plan, and config.

**Comment by iskess** [comment]
Is there a list of shortcuts published anywhere? It would be great to have it somewhere in MP for reference.

**Comment by meee1** [comment]
Main Screen
F2 - FlightData
F3 - FlightPlanner
F4 - Tuning
F5 - Refresh full param list
Control-F - Temp screen
Control-X - sysid selector
Control-T - Blind connect

FlightData
1 - tab 1
2 - tab 2
3 - tab 3
4 - tab 4
5 - tab 5
6 - tab 6
7 - tab 7
8 - tab 8
9 - tab 9
0 - tab 10

FlightPlanner
Control-Z - undo
Control-O - open wp file
Control-S - save wp file

AutoWP Grid
Control-O - open grid file
Control-S - save grid file

**Comment by iskess** [comment]
Thanks Michael. Could this be listed under the help tab?
