### ISSUE TITLE
Mission Planner reporting 2 mavlink packets lost when it is only 1 lost packet

### ISSUE THREAD

**Issue by lbreckenridge** [diydrones/MissionPlanner#1124]
INFO MissionPlanner.MAVLinkInterface - mav 1 seqno 176 exp 175 pkts lost 2
INFO MissionPlanner.MAVLinkInterface - mav 1 seqno 193 exp 192 pkts lost 2
INFO MissionPlanner.MAVLinkInterface - mav 1 seqno 199 exp 198 pkts lost 2
INFO MissionPlanner.MAVLinkInterface - mav 1 seqno 218 exp 217 pkts lost 2

**Comment by meee1** [comment]
please provide a tlog.

**Comment by lbreckenridge** [comment]
[2016-02-03 20-50-16.zip](https://github.com/diydrones/MissionPlanner/files/115420/2016-02-03.20-50-16.zip)
log attached thanks

**Comment by meee1** [comment]
fixed, thanks
