### ISSUE TITLE
Install Firmware page should allow downloading beta and stable firmwares

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#1131]
At the moment, the Install Firmware screen always delivers the "latest" build for Antenna tracker but we've very recently changed the ardupilot build so that it produces "stable" and "beta" versions as well at least for px4 boards (APM boards don't).

Would it be possible to make the "beta firmwares" link get the firmware from:
http://firmware.diydrones.com/AntennaTracker/beta/PX4/

and "stable" get them from here?
http://firmware.diydrones.com/AntennaTracker/stable/PX4/

**Comment by meee1** [comment]
done here
https://github.com/diydrones/binary/commit/f780f22ff8f37c3a8cc43e62bd41d04e33a8c9b5

**Comment by rmackay9** [comment]
Txs very much!
