### ISSUE TITLE
Dataflash log viewer shows incorrect mode from Tracker

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#1133]
When viewing antenna tracker logs with the dataflash log viewer, the modes are incorrect.  Maybe the issue is that we don't have a FLTMODE1 parameter in tracker (because we don't currently allow the user to change the tracker's mode from a transmiter)?

The mapping from mode number to string is here:
https://github.com/diydrones/ardupilot/blob/master/AntennaTracker/defines.h#L14

MANUAL=0
STOP=1
SCAN=2
SERVO_TEST=3
AUTO=10
INITIALISING=16

![tracker_modedisplayincorrect](https://cloud.githubusercontent.com/assets/1498098/12999694/487aa864-d195-11e5-943d-2a113a489ea1.png)

**Comment by meee1** [comment]
this should be fixed now.
