### ISSUE TITLE
Mission planner 1.3.35 - Flight data map window does not show route sometimes

### ISSUE THREAD

**Issue by JeyPi** [diydrones/MissionPlanner#1136]
I might be doing something wrong, but the flight data screen does not show waypoints in its map window as soon as the waypoint distance exceed some measure.
For example if my planned route is within the radius of 2km it is fine. But if I plan a route that is in a radius of 10 Km, the waypoints will not show up. If I want to see the plane following the route I must go to the flight plan window

**Comment by meee1** [comment]
do you have an example?
also do you have "auto pan" turned on?

**Comment by JeyPi** [comment]
Well I can post photographs, or the waypoint file. The mentioned behavior occurred
 several times. It should not be a problem to replicate it.
Here is a missing waypoint. The picture shows the route in the Planning window and below in the flight window
![missing w](https://cloud.githubusercontent.com/assets/16972472/13032741/9976e7cc-d2fe-11e5-821c-2dde316a5c8d.jpg)
The second picture shows no waypoints at all in the flight data window while they are planned in the flight plan window
![no w](https://cloud.githubusercontent.com/assets/16972472/13032747/09182398-d2ff-11e5-90e8-02969a1f149b.jpg)
These will no show up in the flight data window.
[waypoint example](https://www.dropbox.com/s/34k78uyuy1jxsbu/APOK.waypoints?dl=0)

**Comment by meee1** [comment]
normally flight data will only show what has been received or sent to the autopilot. ie if you load a mission and never send it it will never show up.

**Comment by JeyPi** [comment]
Confirmed and closing
