### ISSUE TITLE
Config/Tuning Standard Params ARMING_CHECK's odd "Voltage" checkbox behaviour

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#1145]
On the Config/Tuning >> Standard Params page, checking/unchecking the Voltage checkbox seems to cause the "All" checkbox to becomes unchecked.

Test 1:
- check all checkboxes checked, press "Write Params"
- press "Refresh Params", Voltage checkbox becomes unchecked!

Test 2:
- uncheck all checkboxes, press "Write Params"
- check the "Voltage" checkbox, press "Write Prams"
- press "Refresh Params", all the checkboxes except "Voltage" become checked

**Comment by meee1** [comment]
the root cause is that its a uint_8
AP_Int8         arming_check;

**Comment by rmackay9** [comment]
great, thanks!
