### ISSUE TITLE
display ch3_percent correctly with reverse thrust

### ISSUE THREAD

**Issue by magicrub** [diydrones/MissionPlanner#1146]
When Reverse Thrust is used then the VFR_HUD throttle mavlink msg can be interpreted wrong since it is now abs(throttle). When throttle is negative, the SYS_STATUS bitflag MAV_SYS_STATUS_REVERSE_MOTOR now gets set which tells the GCS to change the sign on the current ch3_throttle value.

see this commit for ArduPilot details: https://github.com/diydrones/ardupilot/commit/d04b5e735fceb481979b37be0b8b903eb3e17bf3

**Comment by meee1** [comment]
Tom, where is the upstream mavlink change for this one?

**Comment by magicrub** [comment]
submodule points to https://github.com/diydrones/mavlink/commit/4a0202b4cbb4179cf6c8566652c27fcbe8130882 and https://github.com/mavlink/mavlink/commit/0798eed89d9306d7c80bc844f4543572f07ce6e9

**Comment by meee1** [comment]
done
