### ISSUE TITLE
Adding new flight mode on my local PC

### ISSUE THREAD

**Issue by amitbed** [diydrones/MissionPlanner#1150]
Hi,
I'm trying to add a new Flight mode to the Mission planner.
I want the flight mode to be defined locally on my device.
I've already added the new flight mode to ArduPilot 
(following these instructions: http://dev.ardupilot.com/wiki/apmcopter-adding-a-new-flight-mode/
), and tried to change the code of the files ParameteMetaData.xml ParameteMetaDataBackup.xml of the Mission Planner to add my new flight mode. 
That didn't help and I'm still seeing the regular flight modes.
What am I doing wrong? and is there a simpler way to add a new flight mode locally?

Thank you very much,
Amit

**Comment by meee1** [comment]
sounds like you have done the correct thing. in the xml files there are multiple sections based on what you are connected to, my guess is you only changed the first section. have another look.
