### ISSUE TITLE
HUD user items stop responding after long missions.

### ISSUE THREAD

**Issue by GrahamDyer** [diydrones/MissionPlanner#1155]
We fly +/-2 hour missions and if we reconnect to the plane to start the second or third mission the user items on the HUD stop updating requiring a MP restart to get everything working again. This started with v1.3.34.

**Comment by meee1** [comment]
is it the same plane every time?

**Comment by GrahamDyer** [comment]
Yes, the planes' batteries get changed so Pixhawk reboots but it's normally the same plane. Upon reconnecting the HUD user items don't update, staying either on 0 or whatever they were last on when disconnected from the plane previously.

**Comment by magicrub** [comment]
Check that the sysid params are the same on the aircraft. Also, how are you
connecting via?

**Comment by GrahamDyer** [comment]
Via RFD900's radio's.

**Comment by iskess** [comment]
I have noticed the same problem. The values freeze when reconnected to the same aircraft. I have to de-select and re-select the user item to get it to work again. I did this a dozen times when trying to troubleshoot the Throttle% for reverse thrust, but forgot to report it. 
(PS. I think throttle% should always be on the HUD, not an optional user item, IMHO)

**Comment by meee1** [comment]
please try the latest beta, i made a mod last night

**Comment by meee1** [comment]
change was here https://github.com/diydrones/MissionPlanner/commit/7e5eae50d85a18185fec863308803fe48d48f043

**Comment by iskess** [comment]
This is still not fixed. The HUD user items were frozen during my whole flight today. I can duplicate while playing back the tlog, by pressing pause, then resuming playback.

**Comment by meee1** [comment]
I might get you to test a change to verify this one.
the tlog playback issue is related to the pausing reset, so not realy a solid link/repeatable.
