### ISSUE TITLE
I can not found meta-data file(MAVLink.dll, MissionPlanner.Utillities.dll, MissionPlanner.Controls.dll, MissionPlanner.Comms.dll)

### ISSUE THREAD

**Issue by sgh055** [diydrones/MissionPlanner#1158]
I download MissionPlanner from git and I can see compile error(not found meta-data)

![image](https://cloud.githubusercontent.com/assets/15629613/13315013/97339348-dbeb-11e5-82f1-87ed1da0ba85.png)

So how can i fix this?

**Comment by meee1** [comment]
please refer to the how to build mission planner on the wiki http://dev.ardupilot.com/wiki/buildin-mission-planner/
