### ISSUE TITLE
dangerous: closing the "Are you sure you want to disarm?" dialog equates to "Yes"

### ISSUE THREAD

**Issue by chapman** [diydrones/MissionPlanner#1166]
If you have an armed drone and you click the disarm button in mission planner it opens a dialog saying "Are you sure you want to disarm?"

If you click Yes, it disarms.
If you click No it cancels the disarm. 
If you close the dialog it also disarms.

This is extremely dangerous, particularly for multi-rotors, and I think it should probably be rectified ASAP.

Closing a confirmation dialog should always equate to the negative/cancel action, particularly in this case.

**Comment by meee1** [comment]
duplicate
https://github.com/diydrones/MissionPlanner/issues/1156
