### ISSUE TITLE
Request QuadPlane Modes support

### ISSUE THREAD

**Issue by SSUAV** [diydrones/MissionPlanner#1169]
Request that the QuadPlane Modes QHover, QLoiter & QStabilize be added to the selectable dropdown lists and the appropriate Qmode appears in the HUD when selected.
ref:http://plane.ardupilot.com/wiki/quadplane-support/

**Comment by meee1** [comment]
added, thanks

**Comment by SSUAV** [comment]
Q-Modes now appear in HUD thanks.
Expected to also be in:
Initial Setup / Flight Mode / Flight Mode # dropdown lists.
Config/Tuning / Full Parameter List. / FLTMode Options
Config/Tuning / Full Parameter Tree. / FLTMode Range
