### ISSUE TITLE
Traditional Heli, Rotor Speed Control Setup

### ISSUE THREAD

**Issue by Fortesque0** [diydrones/MissionPlanner#1170]
Hello:
I found some issues on this versión.

-TRADITIONAL HELI: - On heli setup Window, Rotor Speed Control has not ítems (on SITL too)
![rotor speed](https://cloud.githubusercontent.com/assets/17238988/13606842/eb897a96-e54d-11e5-8416-6754762f7a18.png)

Thanks in advance!

**Comment by magicrub** [comment]
please make separate issues for separate problems.

**Comment by Fortesque0** [comment]
Hello magicrub,
I will do.
Thanks

**Comment by Fortesque0** [comment]
Hello,

Could anyone take a look to this issue?
Thanks

**Comment by meee1** [comment]
please update to latest mp versions.
then goto help > update. to refresh the param list.

**Comment by Fortesque0** [comment]
I did  it yesterday exactly like do you say. From MP 1.35 (Working parameter), to MP 1.37. Star SITL for Helicopter and parammeter doesn´t appears.
I will do today erasing MP folder and downloading Last MP .MSI

**Comment by meee1** [comment]
after installing 1.37, you need to do another update to refresh the param list.

**Comment by Fortesque0** [comment]
Thanks. I did erasing folder and reinstalling. 
I didn't know ctrl-f option. I have been looking on MP wiki about this option, and i didn't find información.
I think its very important to document all changes-options. One more time, i offer myself to help updating the documentación.
I close this issue.
Thanks.
