### ISSUE TITLE
possible bug in advanced grid options (grid v1)

### ISSUE THREAD

**Issue by CharlieGUS** [diydrones/MissionPlanner#1171]
I was testing a few image acquisition plans and I noticed changes I made to the overlap and sidelap settings were not implemented in the mission plan after clicking accept, unless I subsequently change (any) one of the numerical values on the simple grid options tab. 

The projected stats for the flight do not change unless the same step is taken. 

easiest to see with footprints enabled. 

1) make a grid plan, change the overlap setting to an extreme value on the advanced options tab
2) enable footprints on the simple options tab
3) change value of altitude, angle, speed or segments
4) observe overlap setting change made in step 1) is now implemented

Mission Planner v 1.3.36

**Comment by meee1** [comment]
fixed, thanks
