### ISSUE TITLE
Crash when using Joystick on SITL

### ISSUE THREAD

**Issue by Fortesque0** [diydrones/MissionPlanner#1172]
Hello:

When you use SITL and then you change joystick to enabled, Mission Planner crash.

![crash](https://cloud.githubusercontent.com/assets/17238988/13606876/0171a572-e54e-11e5-8f5e-f319b1abe1c5.png) 

Thanks in advance!

**Comment by magicrub** [comment]
Do you have a physical joystick connected? What kind? Is this SITL on windows?

**Comment by meee1** [comment]
what type/brand of joystick are you using?

**Comment by Fortesque0** [comment]
Hello:

The same joystick that i was using on previous misión planner versión without problem, NGS Black Hawk via USB.
Windows and mission planner recognize it as
![joystick](https://cloud.githubusercontent.com/assets/17238988/13617836/f91db504-e580-11e5-9bea-685e03dc70b2.PNG)

**Comment by Fortesque0** [comment]
And i use all SITL options  throught missión planner on Windows 7

**Comment by meee1** [comment]
what was the last version that worked? the joystick code hasn't changed in 4 months

**Comment by Fortesque0** [comment]
On MP 1.3.35 Works fine. I will try to unisnstal and install joystick again.

**Comment by Fortesque0** [comment]
I have unninstall and install again joystick and issue persist. I will reinstal MP1.3.35 and take a shootscreen using SITL and Joystick.

**Comment by Fortesque0** [comment]
Hello,
I have reinstall MP 1.35 and joystick Works fine. I have unninstall MP1.35, delete folders and restart computer. Install MP1.36, configure and safe joystick, and again, MP crashes on SITL when Joystick its selected.

**Comment by meee1** [comment]
done

**Comment by Fortesque0** [comment]
Thanks Michael, now Works.
