### ISSUE TITLE
Arm Checks does not have selectable ítems

### ISSUE THREAD

**Issue by Fortesque0** [diydrones/MissionPlanner#1173]
Hello,

On airplane firmware, the Arm Checks has not selectable ítems

![arm](https://cloud.githubusercontent.com/assets/17238988/13606925/47f3d93e-e54e-11e5-81db-1adef9af04bf.png)

Thanks in advance!

**Comment by meee1** [comment]
fixed, thanks

**Comment by Fortesque0** [comment]
Thanks Michael!
