### ISSUE TITLE
Traditional Helicopter Failsafe Settings

### ISSUE THREAD

**Issue by Fortesque0** [diydrones/MissionPlanner#1174]
Hello,
 I do not know exactly which version stopped working or failed, but in the current and previos versión, this happends.
The failsafe it´s looking for throttle on channel 3, but the throtle input it´s on Channel 8 for traditional helicopters. So the failsafe doesn´t work properly. 
And how will work failsafe throttle ouput, looking for diferents RSC Throttle inputs (Ch8, Dissable or setpoint)??

Thanks in advance

**Comment by meee1** [comment]
is this a Mission planner issue, or a firmware issue? ie what screen I'm mp is wrong?

**Comment by magicrub** [comment]
doesn't sound like a MP problem to me

**Comment by Fortesque0** [comment]
I don´t know if is a MP or Firmware problema. Who set´s the throttle channel? I am taking shot screens, one moment

**Comment by Fortesque0** [comment]
You can see that throttle (cannel 8),its under failsafe set point, but pixhak its not on failsade mode. Channel 3 (Collective pitch on helicopter) its over failsafe point too.
![failsafe1](https://cloud.githubusercontent.com/assets/17238988/13619050/64c8deb8-e587-11e5-95de-46ab7a7014ee.PNG)
Now, you can see that cannel 3 its under failsafe setpoint, and pixhawk goes to failsafe mode
![failsafe2](https://cloud.githubusercontent.com/assets/17238988/13619148/d7be9f7a-e587-11e5-944f-b3c545eaa6f5.PNG)

The same happends if you are using Helicopter sitl . Firmware or MP, i don´t know where it´s the issue.

**Comment by Fortesque0** [comment]
The SITL Helicopter doesn't take off to. Could be this relationated? Cyclic servos output increases, but the heli doesn't moves.

**Comment by rmackay9** [comment]
The failsafe is triggered from channel 3.  So the "Radio 3" needs to go below 1045.  It also won't trigger while the vehicle is disarmed.
This is really a support question about the trad heli firmware not mission planner so doesn't really belong in github (which is for bugs and enhancement requests) so closing.
