### ISSUE TITLE
Virus detected downloading Mission Planner SITL firmwares

### ISSUE THREAD

**Issue by Fortesque0** [diydrones/MissionPlanner#1176]
Hello:
Avast antivirus detects Drep virus when SITL ask for firmwares.
![virus](https://cloud.githubusercontent.com/assets/17238988/13619701/ee7972a0-e58a-11e5-9768-e8daf88e16f5.PNG)

**Comment by meee1** [comment]
DomainRep is a new feature of Avast, so let me explain a bit. It blocks EXE files downloads if these conditions are *all* met:
1. The file is not prevalent enough, ie. not enough Avast users launched the file yet,
2. The domain is not prevalent enough, ie. not enough Avast users downloaded (any) EXE files from the domain yet,
3. The file is not signed or Avast does not trust the signature.

Once one of these conditions are not met anymore, Avast will stop flagging the download. In other words, just wait until more people try to download the file, or digitally sign your files :-).

from https://forum.avast.com/index.php?topic=163221.0

**Comment by meee1** [comment]
it is safe to ignore.

**Comment by Fortesque0** [comment]
Thanks Michael
