### ISSUE TITLE
Request: have checkbox to automatically start video overlay / button on HUD

### ISSUE THREAD

**Issue by dk7xe** [diydrones/MissionPlanner#1180]
with #631 there was the idea by @taedla01 to add 

> A direct button in "Flight Data Screen" for starting video feeding could be a good thing... Perhaps in 
> HUD, when the right mouse button is pressed and a secondary menu appears.

But that was never implemented.
I also have a fixed installed Video Grabber connected to the windows tablet im' using in my FPV/Telemetry case.

For people like me it would be very much appreciated to have either a check box on the config tab (next to Enable HUD Overlay) to automatically start the video overlay or an option in HUD as mentioned by @taedla01.

Thank you!
Gerald

**Comment by meee1** [comment]
latest beta has a option on the right click menu, it is untested
