### ISSUE TITLE
Survey Grid: CAM_TRIGG_DIST not added to beginning of mission 

### ISSUE THREAD

**Issue by jmachuca77** [diydrones/MissionPlanner#1181]
When creating a survey grid and selecting cam_trigg_dist as the cam triggering method, the message is not added to the mission. 
![1978738_10154024673249066_4962563211441034226_n](https://cloud.githubusercontent.com/assets/1664405/13659159/f873012c-e643-11e5-920c-9ed85459657d.jpg)
![12795151_10154024672089066_2604071069931229447_o](https://cloud.githubusercontent.com/assets/1664405/13659187/5be1976e-e644-11e5-87d3-51f123ed9387.jpg)

**Comment by meee1** [comment]
Jamie, your correct, turn on breakup starts as a workaround.

**Comment by ReelAir** [comment]
Cheers Jaime for posting this for me... And thank you Michael for the work around

**Comment by meee1** [comment]
I will push a new beta now, with the fix.

**Comment by ReelAir** [comment]
Cheers Michael.. Your a champ...

Tex
0418102767

Owner/Pilot/Chief Controller

CASA.UOC.0124 

tex@reelairimagery.com.au <mailto:tex@reelairimagery.com.au> 

 <https://www.facebook.com/ReelAirImagery?ref=tn_tnmn>



















+-------------------------- Dyslexic / Dysgraphic  Email Disclaimer -------------------+

I'm Dyslexic / Dysgraphic. Reasonable care has been taken to ensure this
email is legible. However I do not take responsibility for offending you with 
poor spelling or grammar.
 <https://www.facebook.com/ReelAirImagery?ref=tn_tnmn>
 <https://www.facebook.com/ReelAirImagery?ref=tn_tnmn> <https://www.facebook.com/ReelAirImagery?ref=tn_tnmn>http://en.wikipedia.org/wiki/Dysgraphia <http://en.wikipedia.org/wiki/Dysgraphia>        http://www.dyslexia.com/famous.htm <http://www.dyslexia.com/famous.htm>

**Comment by jmachuca77** [comment]
Working on the latest beta. Break up starts -> this is for not taking pictures during turns?

**Comment by meee1** [comment]
@jmachuca77 correct, trig dist is turned off and on at the start and end of each line
