### ISSUE TITLE
GridUI doesn't close and grid isn't generated properly if split is > 1

### ISSUE THREAD

**Issue by akorb** [diydrones/MissionPlanner#1182]
![preview](https://cloud.githubusercontent.com/assets/6689889/13663933/bcbd5e46-e6a4-11e5-995a-b307eeb7b159.PNG)

1. Split more than 1
2. Accept
3. GridUI stays open
4. Mission items are partially generated
5. If GruidUI closed manually, the generated mission items are not drawn

**Comment by meee1** [comment]
thanks for the report, you must be running beta. I'm uploading a new beta atm.

**Comment by akorb** [comment]
Built the latest Mission Planner by myself.
Glad I could help.
