### ISSUE TITLE
Altitude changes when dragging waypoint

### ISSUE THREAD

**Issue by garrinfelber** [diydrones/MissionPlanner#1183]
Hi. When I enable "verify height" in the mission planner, it adjusts the altitude correctly when creating waypoints "left mouse click". However, if I then drag one of those waypoints to move it, the altitude changes to what I guess is ASL. 

For example, if I have default altitude at 100, I place a waypoint and it automatically sets it to alt=102. If I drag it a few "meters" over, it changes to 462. Moving that waypoint around will have it change to 459, 463, etc.

**Comment by meee1** [comment]
what is your home altitude set to? it should be 362?

**Comment by garrinfelber** [comment]
Home altitude set to 371.

**Comment by meee1** [comment]
looks like it is a bug.

**Comment by iskess** [comment]
See #736

**Comment by meee1** [comment]
done
