### ISSUE TITLE
EKF and Vibe in HUD can not be turned back on

### ISSUE THREAD

**Issue by Jman841** [diydrones/MissionPlanner#1188]
The latest version of Mission Planner states it allows you to add and remove the EKF and Vibe information in the HUD, however, I can not find anywhere in mission planner to Turn this feature on/off.

**Comment by meee1** [comment]
its an internal function. its not meant for general users

**Comment by Jman841** [comment]
I find these indicators very useful, especially with Quadcopters and helicopters as I can check to see if there is clipping issues with the pixhawk when building a new quadcopter and check vibrations easily during flight. And I can see if there is compass errors right away with the EKF indicator.

Is there any way we can make these optional to be used/visible in the HUD again?

**Comment by meee1** [comment]
I'm fixing atm, they are meant to be on. you will get another update request very soon.

**Comment by Jman841** [comment]
Ah ok, Thank you very much. Sorry for the misunderstanding.

**Comment by meee1** [comment]
thanks for the report!!!
