### ISSUE TITLE
Helicopter FF in Extended tuning is not working with current version

### ISSUE THREAD

**Issue by Jman841** [diydrones/MissionPlanner#1190]
The current version of Mission planner with the latest version of Arducopter Traditional Heli does not work for changing the Feed Foward parameter in the Extended tuning screen. Now that we have the latest version of Traditional Heli I believe we can fix this and not have issues with the name changes for the parameter like we did in the past.

Thank you,

Jason

**Comment by meee1** [comment]
in the latest MP
please press control-f
then click param gen.
restart mp, and it should be resolve

**Comment by Jman841** [comment]
Just tried that but didn't seem to work. the FF param is still blanked out and can't change it from the extended tuning page.
