### ISSUE TITLE
Mission Planner won't connect to SITL running gimbal

### ISSUE THREAD

**Issue by trondhindenes** [diydrones/MissionPlanner#1191]
If starting SITL (arducopter.elf) with the --gimbal option, mission planner refuses to connect (at least over tcp, which is what I've tried). Everything works if I remove the "--gimbal" parameter when starting arducopter.elf. Is this a mission planner bug or a simulator bug?

**Comment by meee1** [comment]
I don't believe this is a MP issue, but an issue with the simulator.
I believe this is something to do with a tcp timeout on connect.
