### ISSUE TITLE
Plugins don't load globalized resources

### ISSUE THREAD

**Issue by kjeremy** [diydrones/MissionPlanner#1201]
If a plugin contains translated text in a resource file (ex. `Resources.resx` and `Resources.ko-KR.resx`) the translation does not load.

Recommendations online suggest loading plugins with `Assembly.LoadFrom` instead of `Assembly.Load`.  However there was a report of this breaking plugins in #1192.

**Comment by meee1** [comment]
fixed 630065701d76bb382cac21826f5c46c65f728b94

**Comment by kjeremy** [comment]
Thanks!  It works.
