### ISSUE TITLE
Compass calibration not subtracting offsets for 2nd compass

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#585]
The Live compass calibration doesn't appear to be subtracting the compass offsets for the 2nd compass.  This leads to every other calibration being incorrect.

![randybadcompass](https://cloud.githubusercontent.com/assets/1498098/3941005/e60edcc4-2504-11e4-8b83-456ff38f9232.png)

**Comment by rmackay9** [comment]
surely this is fixed.

**Comment by meee1** [comment]
yes here 57ac046502b435552549da09c3f9a470b81a55aa
