### ISSUE TITLE
No camera trigger relay output on PixHawk? Interaction with BRD_PWM_COUNT parameter?

### ISSUE THREAD

**Issue by airborneimager** [diydrones/MissionPlanner#603]
It is not clear whether or how a user can set up the PixHawk to generate a digital ("relay") output for a camera trigger, as opposed to a PWM output. The CAM_TRIGG_TYPE parameter is still present and active, but setting this to 1 doesn't appear to enable any of the six output channels 50-55 as a digital output line - they all still seem to be PWM outputs.

There does not appear to be any documentation on this issue, either. The only sentence in the documentation which alludes to this at all is "If you select “Relay” from the drop-down, then pin A9 on the APM2 will be pulled high to trigger the camera’s shutter" (first paragraph in http://copter.ardupilot.com/wiki/common-camera-shutter-with-servo/). It isn't clear whether the omission of any reference to this functionality on the PixHawk is because the documentation was written before the PixHawk was developed, or is an implicit way of saying that there is no such function on the PixHawk.

Moreover, it is not clear how the CAM_TRIGG_TYPE setting interacts with the setting of BRD_PWM_COUNT, e.g., if BRD_PWM_COUNT is set to 6, enabling all six outputs as PWM, how can one of them be set by CAM_TRIGG_TYPE to be a digital output?

Can someone please explain this, and consider updating the documentation to make it clear to users how to trigger cameras with a digital output instead of a servo pulse on the Pixhawk?

**Comment by AdrianEvans** [comment]
Pixhawk - Does anybody here know how to change the length the signal is pulled up/down for? I've set this up via channel 7 on a switch - on switching it pulls but only for a very short period. It would be good if this could be lengthened.

**Comment by rmackay9** [comment]
@AdrianEvans, If you're using the camera shutter feature in ArduCopter there's a "Duration" field in the mission planner's Camera Gimbal page.
http://copter.ardupilot.com/wiki/common-camera-shutter-with-servo/

**Comment by rmackay9** [comment]
Now that AC3.2 has gone out I think we can close this issue.  Relays on Pixhawk work on AC3.2.

**Comment by airborneimager** [comment]
Randy - I'll take it on faith that relays work on Pixhawk in AC3.2. My only
concern now is that the documentation clearly reflects that this is only
true if BRD_PWM_COUNT is set such that the chosen relay line is not set to
PWM. This was what tripped me up at first, until I came to understand that
the output lines were essentially independently configurable as either PWM
or hi/lo via BRD_PWM_COUNT.

**Comment by rmackay9** [comment]
@airborneimager, I've updated the Relay wiki page so hopefully that covers it: http://copter.ardupilot.com/wiki/common-relay-2/
