### ISSUE TITLE
Increase image detail on firmware page.

### ISSUE THREAD

**Issue by JaredReabow** [diydrones/MissionPlanner#642]
Hi my workshop has no internet so a new build is a pain when it comes to motor port numbers.
please replace the low res images in firmware with high res that show motor rotation and port numbers, it makes perfect sense.

**Comment by meee1** [comment]
I don't have any plans to change this, as it add unrequired bloat to MP. which I try and avoid.

**Comment by JaredReabow** [comment]
I entirely disagree, 2mb more and we get pictures with a resolution decent enough to read the numbers and see rotation.
It is unprofessional that the software does not include something as basic as that.
You say unrequired bloat but that is rubbish, the motor number and rotation IS REQUIRED.
2m is not going to make or break Missionplanner.
if you were to ask people i could almost guarantee the majority would agree it is useful.

**Comment by JaredReabow** [comment]
because the motor port number and rotation constantly changes...
Did you not read why the wiki is no help.

**Comment by rmackay9** [comment]
@JaredReabow,
"unprofessionaly"?  That's really not polite.

**Comment by JaredReabow** [comment]
sorry, yes it is rude, i am annoyed because of it being called unrequired bloat and dismissed after being a open issue for months, bam closed with a poor reason for closing too. 
As i clearly pointed out, it has a requirement, first and foremost if you don't know where you are going to find the motor layout, it is not a simple matter of "its on the wiki" as the wiki only shows some layouts on one page, you have to click on link after link to find the layout page then find yet another link for the full set of images for octos ,
A not obvious link  vs click firmware tab, upload firmware i want, use firmware images which have the info i need to wire the multi rotor or airplane etc.
no need to drive to the nearest area with reception to then search through the wiki on my phone.
