### ISSUE TITLE
Antenna Tracker setup screen

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#671]
We're making decent progress on getting the antenna tracker working.  If possible I'd like a configuration screen in mission planner to set-up the antenna tracker.  Below is a possibel mockup with the parameters for each field listed in red.

There is one slightly tricky part which is the "Test" button and the slider beside it.  If possible I'd like to get it so the user moves the slider around and then pushes the "Test" button and a DO_SET_SERVO command is sent to the antenna tracker and it moves immediately to that position.  I have the code ready in a branch (antenna-wip6) which accepts these commands.

![antennatracker_mpsetup_design3](https://cloud.githubusercontent.com/assets/1498098/4526288/dd35cf00-4d5d-11e4-88ed-128992d700e5.png)

If possible this screen should only be displayed if the MP is connected to an antenna tracker.

**Comment by meee1** [comment]
done here 20a00bd8
