### ISSUE TITLE
Beta stays "Connected" when usb connection to Pixhawk is disconnected

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#687]
Steps to recreate the problem:
1. connect latest beta mission planner (Ver 1.3.10 build 1.1.5397.23504) to a Pixhawk running ArduCopter 3.2.-rc13
2. disconnect the USB cable (but don't touch the "Disconnect" button)
3. the "Disconnect" button remains (it should disconnect and then change to "Connect")
If I now manually hit the "Disconnect" and "Connect" again I'm unable to connect to the Pixhawk.  The only way to reconnect is to restart the mission planner (I think).

**Comment by meee1** [comment]
same as #744
