### ISSUE TITLE
Add dashed flightlines on flight data screen -only shown on flight plan.

### ISSUE THREAD

**Issue by nicksargeant** [diydrones/MissionPlanner#688]
Minor issue (or perhaps an intended feature) but the dashed line for outbound and return flightlines on the Flight data screen are not dashed as they are on the Flight plan screen. The dashed lines make it far easier to see the intended mission path if flightlines cross. See below pictures:
![image](https://cloud.githubusercontent.com/assets/5547169/4766383/b1fcd1f8-5b4f-11e4-8165-97b2d21bbf10.png)
![image](https://cloud.githubusercontent.com/assets/5547169/4766384/b3c8d31a-5b4f-11e4-8638-aceb48d6dcda.png)

Thanks!

**Comment by meee1** [comment]
done 70a80ce7
