### ISSUE TITLE
Snapping to home on mission/polygon clear

### ISSUE THREAD

**Issue by nicksargeant** [diydrones/MissionPlanner#690]
Minor usability tweak; When mission planning, I have found it quite irritating when clearing a mission or polygon and the map view snaps back to the home position at a defined zoom level. In most cases, it would be better if the view stayed where it was. Would it be possible to disable snapping to home (or perhaps have this as a setting in Config/Tuning->Planner)?
Thanks as always!

**Comment by meee1** [comment]
ive removed snap zooming, but left snap to home
