### ISSUE TITLE
Undo button for Flight Plan screen

### ISSUE THREAD

**Issue by nicksargeant** [diydrones/MissionPlanner#692]
If possible, It would be very useful to have "Undo" button that could fix if a user accidentally moves, changes or deletes a waypoint. All too often, I have had to clear a mission and start planning again after making a simple bungle on a dodgy laptop trackpad out in the field.

Thanks!

**Comment by pwynne** [comment]
+1

**Comment by meee1** [comment]
fffcea1651302c5f575cee15cac41574b00c1e1b
