### ISSUE TITLE
Addition of DOT/FAA aviation reference charts to map views

### ISSUE THREAD

**Issue by CP44** [diydrones/MissionPlanner#695]
Can be tagged as enhancement/feature...

Ability to switch map graphics between common mapping services like OpenStreetMap, Google, Yahoo, etc. and actual flight charts would be a great assistance in avoiding airspace based on airports, approach routes and airways outside of an airport's core airspace, and so on.  Also important for TFRs - see below.  I expect that it would also be of use for coordinating flights or events with air traffic control by having reference points that the aviation system cares about.  (A conversation about model/UAS traffic planned "at 6 nautical miles out from the 313 degree radial of Dupont/DQO VOR with a radius of a half mile" is probably a lot more useful to controllers, coordinators, and people reading NOTAMs and dealing with charts than "at the park at Polly Drummond Hill and Paper Mill Rd".)

Temporary Flight Restrictions (TFRs) are also of interest, and I will use the real park example above along with this real NOTAM, http://tfr.faa.gov/save_pages/detail_4_6076.html , which specifically forbids the following activity in point C: "flight training, practice instrument approaches, aerobatic flight, glider operations, seaplane operations, parachute operations, ultralight, hang gliding, balloon operations, agriculture/crop dusting, animal population control flight operations, banner towing operations, sightseeing operations, maintenance test flights, **model aircraft operations, model rocketry, unmanned aircraft systems (UAS),** and utility and pipeline survey operations. " [emphasis added for Markdown format]

I have not tried Google earth overlays, but I have not seen a system yet that combines ground/road maps with aviation charts to prevent having to use multiple maps/charts with each point defined at Lat/Lon to cross between the systems.  The site http://skyvector.com/ and its unofficial flight plan ability were used for the sample above.  Although that may not support embedding or may refuse to be embedded in Mission Planner type projects, their ability to combine and display VFR sectional, IFR charts, and TFR charts makes them a useful reference for aviation planning - even if not an official platform for navigation.

**Comment by meee1** [comment]
the jeppesen data has been added.

**Comment by CP44** [comment]
Awesome; I noticed what looked like TFR data showing up!
