### ISSUE TITLE
Better fit for different font sizes

### ISSUE THREAD

**Issue by GrahamDyer** [diydrones/MissionPlanner#712]
![space](https://cloud.githubusercontent.com/assets/3287001/5086988/912358cc-6f2b-11e4-9f3f-e5e2cd7a7ca1.JPG)
Some of the words don't fit well in the example image above, especially just below the green word 'Waypoints'.
I'm using a larger Windows font to see on a smaller screen but it would be nice if everything fitted better.

**Comment by meee1** [comment]
there is just not enough screen space to fit it all. there is not a lot I can realy do.
