### ISSUE TITLE
Warn: Full parameter Tree auto-completes values 

### ISSUE THREAD

**Issue by emilecastelnuovo** [diydrones/MissionPlanner#714]
In the full parameter Tree when entering values the textbox gets filled with values that are already present in the list.
This could cause a potential issue if not seen.

The full parameter list does not have this issue.

Emile

**Comment by emilecastelnuovo** [comment]
Sorry, missed your reply...
If I start writing a number that already exists in the full parameter tree, Planner tries to autocomplete it like in the picture below. 
I just wrote 45 and it autocompletes to 4500

![image](https://cloud.githubusercontent.com/assets/3082828/5615831/4b8f0b2c-94ff-11e4-9202-ba10b347019e.png)

**Comment by meee1** [comment]
done.
