### ISSUE TITLE
 Very poor quality connection link after upgrading to MP 3.1.11

### ISSUE THREAD

**Issue by osmunda** [diydrones/MissionPlanner#742]
I already have asked about it in APM forum (http://ardupilot.com/forum/viewtopic.php?f=12&t=10528&p=26243#p26243)  without solution but maybe I should do it here instead.

I don't know what happens with connection link (Link Stats) through 3Dr radios but now I have a very poor connection link (less than 16%) and a lot of packets lost. That happens at home, with Air and Ground radios close together and with no problems of noise nir remnoise.

I don't know exactly when that start to happen but I think I have that problems after Mission Planer Upgrade to 3.1.15 or Arducopter and Arduplane firmware upgrade to 3.2 (I did all at the same time).

That happens both with my airplanes and quadcopter. I am using APM 2.6 and 915 3DR radios (original), 915 RC timer radios or RDF900 radio modem. The same issue in all cases. I didn't change any config parameter related to serial connection from previous versions of MP or Arducopter-Arduplane.
![badquality_example2](https://cloud.githubusercontent.com/assets/3528034/5329734/00f26222-7dc0-11e4-9ba6-5ff5ed858718.PNG)

I tried to upgrade radios firmware again (Sik 1.9) but I still have the same problem. By the way, radios were configured with Airspeeed 48, ECC, Mavlink protocol (more or less the default configuration, that also has been tested).
![badquality_example_radiosconfig](https://cloud.githubusercontent.com/assets/3528034/5329735/0b018e96-7dc0-11e4-948c-65c6404cfd82.JPG)

And finally, after some tests with previous MP versions I have detected that this problem with Mavlink quality actually started with version 3.1.11. With MP 3.1.10 link quality is 100% and after upgrade it to 3.1.11 it drops to 16%, as I reported in my first post.

I also have checked MP Change Log and I notice that version 3.1.11 included a new Mavlink library.
Am I the only one with this problem? After searching for solution in APM forum I can't understand what is happening.

Any help is welcome.

**Comment by meee1** [comment]
this has been fixed

**Comment by osmunda** [comment]
Great! Thank you very much

**Comment by itayguy** [comment]
Hi , can you refer me to the solution?
I think I have this problem.
