### ISSUE TITLE
Optical flow data in Status tab and tuning windows

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#745]
AC3.3 will include sending optical flow data down to the ground station using the OPTICAL_FLOW mavlink message. http://mavlink.org/messages/common#OPTICAL_FLOW

To allow users to easily test that the optical flow sensor is using, it would be good to display the optical flow data through the mission planner's Flight Data screen's status tab and tuning window.

**Comment by rmackay9** [comment]
We're pretty much ready for people to start testing the optical flow sensor with AC3.3 so it'd be nice to get this optical flow data displayed in the mission planner to make testing easier.  Not super urgent but..

**Comment by meee1** [comment]
in the optical flow message, which values are important?

        /// <summary> Timestamp (UNIX) </summary>
        public  UInt64 time_usec;
            /// <summary> Flow in meters in x-sensor direction, angular-speed compensated </summary>
        public  Single flow_comp_m_x;
            /// <summary> Flow in meters in y-sensor direction, angular-speed compensated </summary>
        public  Single flow_comp_m_y;
            /// <summary> Ground distance in meters. Positive value: distance known. Negative value: Unknown distance </summary>
        public  Single ground_distance;
            /// <summary> Flow in pixels * 10 in x-sensor direction (dezi-pixels) </summary>
        public  Int16 flow_x;
            /// <summary> Flow in pixels * 10 in y-sensor direction (dezi-pixels) </summary>
        public  Int16 flow_y;
            /// <summary> Sensor ID </summary>
        public  byte sensor_id;
            /// <summary> Optical flow quality / confidence. 0: bad, 255: maximum quality </summary>
        public  byte quality;

**Comment by rmackay9** [comment]
the 4 flow rates and the quality:
flow_comp_m_x
flow_comp_m_y
flow_x
flow_y
quality

**Comment by meee1** [comment]
done

**Comment by rmackay9** [comment]
Great, thanks very much!
