### ISSUE TITLE
Loss of telemetry without warning

### ISSUE THREAD

**Issue by varosi** [diydrones/MissionPlanner#746]
1. Go to Initial Setup | Wizard | 3DR Radio
2. Load Settings
3. Change Air Speed on the Local or Remote only radio

This will make telemetry link down. Which was not expected by me. I just didn't know that radios cannot work at different speeds in different directions. 

It will be great if there is some warning message (question dialog) about changing to non-compatible settings between two 3DR radios (local and remote).

**Comment by meee1** [comment]
added note here 27083699

**Comment by varosi** [comment]
This note is not preventing you from failing easily.
It's good if there is a modal dialog with a question to do that.

2015-01-05 15:21 GMT+02:00 Michael Oborne <notifications@github.com>:
