### ISSUE TITLE
WP Table Scrunched Up in lefthand corner 1.3.16

### ISSUE THREAD

**Issue by 1Steven** [diydrones/MissionPlanner#752]
I just updated to MP 1.3.16 and found the WP table on the Flight Planning tab, is all scrunched up in the left hand corner. It's impossible to see or use. Please fix.
Regards,
Steven

**Comment by meee1** [comment]
this should be resolved in the latest beta.

**Comment by meee1** [comment]
change here 16cd7a16

**Comment by barneyliftoff** [comment]
I saw that you released a revised version the day after I sent in my complaint.  I appreciate your quick response.  Thanks

Bernie Liskov

**Comment by 1Steven** [comment]
Thank you. However the function column is still truncated for me. In other words, Waypoint comes out Way...
It might just be me as I use a Toughbook which 4x5 aspect ratio. 
Regards 
Steven
