### ISSUE TITLE
dataflash download windows doesn't have scroll bar in log size display

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#761]
When the number of dataflash logs becomes very large it's not possible to see the bottom items unless the user resizes the window.  There should probably be a scroll bar.
![df-download-scrollbar](https://cloud.githubusercontent.com/assets/1498098/5574774/b56a6e1c-900c-11e4-80af-4445a1bb479d.png)

**Comment by meee1** [comment]
done 323effab
