### ISSUE TITLE
Compass Declination Error !

### ISSUE THREAD

**Issue by kkopters** [diydrones/MissionPlanner#762]
I have decide something for this issue why can't we make it as for west press "W" and for the east we can press "E" after entering the declination in the Mission planner is that a bad idea ? still Iam entering through manual it's still Error ! 
If still there is an any confusion please follow this link 
http://diydrones.com/group/arducopterusergroup/forum/topics/compass-declination-error?xg_source=activity

**Comment by meee1** [comment]
mod here 89e31ef9
