### ISSUE TITLE
Can the command 'DO_SET_ROI ' be added to Mission Planner with software of ArduPlane

### ISSUE THREAD

**Issue by tsq1988** [diydrones/MissionPlanner#763]
With software of ArduPlane, I want my 3 axis gimbal to point ROIs,just like the Copter with 3.2 firmware. The code of plane does include the mavlink command DO_SET_ROI, but when i did a flight mission in MP,  waypoints can't be set to ROI. Can this command be added to MP when firmware is Plane?

**Comment by meee1** [comment]
will be in next mp release
