### ISSUE TITLE
bug: mission polygon not deleted after changing mission and writing it on the planner

### ISSUE THREAD

**Issue by itayguy** [diydrones/MissionPlanner#765]
![bug](https://cloud.githubusercontent.com/assets/4155188/5602454/ce5e1af2-9356-11e4-893f-06c3e0cd7a3d.png)

**Comment by meee1** [comment]
is that in flightdata or flight planner?

**Comment by itayguy** [comment]
In the flightdata .
the flightplanner works fine.

**Comment by meee1** [comment]
this relates to 490f1e9c, and should be fixed in the beta.
