### ISSUE TITLE
Distance to MAV

### ISSUE THREAD

**Issue by SSUAV** [diydrones/MissionPlanner#768]
Unable to obtain a range to aircraft on Quick Tab by either Dist to MAV, Dist to Home, DistRSSIRemai.
Dist to Mav is missing in "Display this" option box.
APM 3.2.0 MP 1.3.17.1 build 1.1.5478.13250

**Comment by meee1** [comment]
dist to mav, and dist to home are the same thing.

**Comment by meee1** [comment]
as a work around, make sure you read the wp list back before you fly, and it should work.
