### ISSUE TITLE
Building MissionPlanner project occur errors,how to get the plugings of gstreamer-sharp? 

### ISSUE THREAD

**Issue by zhxzsh** [diydrones/MissionPlanner#772]
When I build MissionPlanner project,ocurr some error:"can found the name space "Gst" ",In GstreamerHUD,a module gstreamer-sharp cannot be found.How to get and install the module(gstreamer-sharp)?thanks!

**Comment by meee1** [comment]
just unload that project for now.

**Comment by zhxzsh** [comment]
"just unload that project for now." ,unload GStreamerHud project?

**Comment by zhxzsh** [comment]
I notice that "Mono.Data.SqliteClient","Mono.Security","MySql.Data","Npgsql","System.Data.SQlite" not found,there are some program packages missing.where get that package?thanks!

**Comment by meee1** [comment]
none of them are required because of the build options used.
