### ISSUE TITLE
[PLANE] Mission Command DO_CONTINUE_AND_CHANGE_ALT missing

### ISSUE THREAD

**Issue by iskess** [diydrones/MissionPlanner#776]
In APM:Plane 3.2.0 support for mission command DO_CONTINUE_AND_CHANGE_ALT was added in conjunction with the new autolanding code. It is not yet supported by Mission Planner.

**Comment by meee1** [comment]
I don't see this in the mavlink standard yet, so cant implement.

**Comment by tridge** [comment]
Hi Michael, the msg is here:
https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/common.xml#L573
sorry for not pointing you at this earlier
