### ISSUE TITLE
MIssion planner red maps and connection failure

### ISSUE THREAD

**Issue by ronhogwarts** [diydrones/MissionPlanner#783]
When mission planner is started I regularly have a red translucent layer appear over the map (the layer is much darker than the airport circles), which disappears when the map is zoomed. Also in this situation I am unable to connect to APM via telemetry. If the map is zoomed it then seems to connect and function normally. See the photo below for details:

![untitled](https://cloud.githubusercontent.com/assets/6254189/5923589/8c35662c-a64c-11e4-9cb8-cfbbb73c3a35.png)

**Comment by meee1** [comment]
this should be fixed here b69a32d6aa710e7fd39f3e24e47075bf2e9b6df7
