### ISSUE TITLE
Survey tool issues v1.3.18

### ISSUE THREAD

**Issue by francisco3dr** [diydrones/MissionPlanner#784]
Tried to make a survey grid on this section.

![map_mission_1](https://cloud.githubusercontent.com/assets/10744619/5942222/123d1674-a6cb-11e4-86f9-74ea119ddcfd.JPG)

It was MP v1.3.17, it works fine on this version.

If I try to make the same mission on MP 1.3.18 it will yield this result.

![map_mission_error](https://cloud.githubusercontent.com/assets/10744619/5942251/328fa5e0-a6cb-11e4-9005-a65a22dade2f.JPG)

**Comment by meee1** [comment]
please try updating to the beta. if all is good I will push a new mp version

**Comment by francisco3dr** [comment]
Ok, so it seems that the Beta version will allow me now.

![map_mission_beta](https://cloud.githubusercontent.com/assets/10744619/5949576/18319972-a704-11e4-876c-59a236560eff.JPG)

Thank you for the help.
