### ISSUE TITLE
Pass through Radio setup failing to connect

### ISSUE THREAD

**Issue by proficnc** [diydrones/MissionPlanner#785]
The feature that allows for the radio to be setup via mavlink is not functioning.  (Radio connected via serial 1 to pixhawk, Pixhawk connected to mission planner via USB)

Radio can be configured via a direct usb connection, but not via pixhawk when connected.

**Comment by rmackay9** [comment]
I've noticed this as well with a somewhat recent MP beta and AC3.2 (or later) firmwares.  I haven't tried with stable mission planner.
