### ISSUE TITLE
Error when Disarming in Auto Mode

### ISSUE THREAD

**Issue by SSUAV** [diydrones/MissionPlanner#789]
On Disarming while in Auto Mode, i.e after Auto Landing, The error message ""verify_nav:Invalid or no current......" appeares on HUD and Throttle goes to full (GCS failsafe on). Does not happen if switch to FBWA or Manual Modes before disarming.

Arduplane: V3.2.0
MP 1.3.18 build 1.1.5503.19823

**Comment by meee1** [comment]
this will be a firmware issue, please post on the ardupilot issue list
