### ISSUE TITLE
Bug: Missing DO_LAND_START and DO_CONTINUE_AND_CHANGE_ALT

### ISSUE THREAD

**Issue by iskess** [diydrones/MissionPlanner#792]
I no longer see the DO_LAND_START or DO_CONTINUE_AND_CHANGE_ALT mission commands.

![no do_land_start](https://cloud.githubusercontent.com/assets/4913946/6031821/a086549c-aba6-11e4-9163-2663041e537b.jpg)

**Comment by meee1** [comment]
are you connected to a copter or plane?

**Comment by meee1** [comment]
that list in the screenshot is for copter

**Comment by iskess** [comment]
Thanks for pointing this out. I'm using a plane, but hadn't connected yet since I was using a desktop computer for flight planning. I'll click the hidden secret button on the upper right and switch to Plane. 
Sorry, I should have figured this one out myself.
