### ISSUE TITLE
Request: UI changes for display of waypoints

### ISSUE THREAD

**Issue by nicksargeant** [diydrones/MissionPlanner#798]
Hello all. 
I hope I am not the only one that gets confused but when planning complicated missions such as those with many waypoints or when using alternating flight lines. Interpreting the mission the screen can become very difficult: 
![flightlines](https://cloud.githubusercontent.com/assets/5547169/6143391/f4755564-b202-11e4-9d48-f63ff6ca804d.PNG)
I am by no means an expert when it comes to UI design but I believe there may be a few minor tweaks that could improve the user experience.  Firstly having the waypoint number offset to the top right of the actual waypoint can be confusing when they are bunched: 
![1](https://cloud.githubusercontent.com/assets/5547169/6143397/0bc88b96-b203-11e4-912c-29464f08b2ea.PNG)
Removing the right hand offset or the separate waypoint number box entirely would make things more readable:
![3orig](https://cloud.githubusercontent.com/assets/5547169/6143406/38ab5076-b203-11e4-9c49-c544bc76fc3b.PNG) -> ![3fix1](https://cloud.githubusercontent.com/assets/5547169/6143407/3a122e1c-b203-11e4-8ab7-ba9a45417455.PNG) OR ![3fix](https://cloud.githubusercontent.com/assets/5547169/6143408/3c0d3888-b203-11e4-9ac9-2a392693c8e4.png)
Alternatively, perhaps the number boxes should be hidden unless the mouse is hovered over the individual waypoint?
Additionally, It would be nice of there were direction arrows mid waypoint to show the flight direction:
![fixarrow2](https://cloud.githubusercontent.com/assets/5547169/6143428/852c29fc-b203-11e4-8a94-394c5e5a3a90.png)

If implementing this, the UI may break if using alternating flightlines so perhaps arrows are only needed along the long flightlines: 
 ![fixarrow](https://cloud.githubusercontent.com/assets/5547169/6143412/46ea47e6-b203-11e4-95bc-a88af859fa94.PNG)
Thoughts?

**Comment by iskess** [comment]
+1
Thanks for bringing up this frustration. Most importantly the WP number offset. I would like the number inside the marker. It can be very small and grow bigger if the pointer hovers over it. This will behavior will also indicate that the WP will be moved if clicked rather than a new WP created. 
I like you direction arrow idea. Only on the long legs. We want the arrows to be subtle and thin to avoid more clutter.

**Comment by nicksargeant** [comment]
Agreed iskess, by no means to I want to make the UI more cluttered however I believe small, unobtrusive arrows would be of benefit. Ideally you could be able to turn them on/off in the missionplanner configuration.

**Comment by meee1** [comment]
please check the latest beta. nothing set in stone yet, but testing ideas

**Comment by iskess** [comment]
I'm away from a computer for a few days, Nick, can you post a screen shot of the beta?
Thanks!

**Comment by nicksargeant** [comment]
Thank you very much @meee1! I think this greatly increases the ease of interpretation. @iskess, apologies for the delay. I have attached two screenshots, one of the original complex flightplan and  another that is a more conventionally shaped polygon. 
![fixed](https://cloud.githubusercontent.com/assets/5547169/6551888/475e676c-c67a-11e4-9026-c9e17bfb5453.JPG)
![fixed2](https://cloud.githubusercontent.com/assets/5547169/6551890/49ab1c5e-c67a-11e4-9984-5f8e1e757573.JPG)
What are your thoughts?

**Comment by nicksargeant** [comment]
My only comment could be that perhaps black text (instead of red) would offer more contrast for the waypoint numbers?

**Comment by iskess** [comment]
I think it is great! Thank you Michael.
