### ISSUE TITLE
Auto analysis failure

### ISSUE THREAD

**Issue by ronhogwarts** [diydrones/MissionPlanner#802]
On Mission planner 1.3.16 Auto analysis for the datalog flash files is reporting "Specified method is not supported", and then "bad input file". I am feeding it a "NearlyAll" APM 2.6 .log file as linked below, and this file opens fine on the manual review log option, and the APM log file analyser.

https://drive.google.com/file/d/0B6QFq1-xwWDSOXBGa1hlMWxCdU0/view

**Comment by meee1** [comment]
please update to the latest MP.

**Comment by ronhogwarts** [comment]
It turned out Mission planner hadn't been auto updating for some reason, despite an internet connection.
