### ISSUE TITLE
Max. waypoints issue with Pixhawk

### ISSUE THREAD

**Issue by buckker** [diydrones/MissionPlanner#805]
The Pixhawk should be able to store 718 waypoints. It's possible to send the waypoints to the Pixhawk. But if you try the send them back to the mission planner, only between 90 and over 200 waypoints come back.

For more information: http://diydrones.com/forum/topics/number-of-waypoints?commentId=705844%3AComment%3A1914581

Thanks

**Comment by meee1** [comment]
fixed in current beta
