### ISSUE TITLE
Auto disable the cam trigger in the "overshoot" path (dynamic CAM_TRIG_DIST)

### ISSUE THREAD

**Issue by robustini** [diydrones/MissionPlanner#806]
During automatic mission with the "survey grid" generator often have to use a overshoot path to allow the plane to execute the turn and get back on course for the new line in the opposite direction.
The CAM_TRIG_DIST parameter is set automatically by the Planner considering many factors, unfortunately is maintained until the end of the mission and in this way produce shots with the camera that are not useful for the photogrammetric purpose based on the defined polygon, i mean when the plane execute the turn out of the polygon.
It would be useful an option to do so in order to auto set CAM_TRIG_DIST to zero, perform the overshoot and set it back to the previous right value as soon as the plane passes the first point useful to photograph.
This would eliminate many shots taken that would not be necessary.
This feature of course is not needed with the copter.

**Comment by robustini** [comment]
![immagine](https://cloud.githubusercontent.com/assets/3864712/6404094/8f5297e6-be14-11e4-8973-a100ffd7edd0.png)

**Comment by robustini** [comment]
@meee1: hi Michael, no news about this?

**Comment by robustini** [comment]
I hope it's clear my concept, disable the cam trigger in the overshoot area (marked in purple rectangles), as not interested and produces many useless photos.

![overshoot](https://cloud.githubusercontent.com/assets/3864712/10413692/c07df10c-6fb3-11e5-907a-52a5697715dc.png)

**Comment by iskess** [comment]
Are you proposing that the Survey tool automatically adds two DO_SET_CAM_TRIGG_DIST commands for each turn?

**Comment by saruban** [comment]
i want to change the theme(such as colors) of this mission planner software for my learning purpose. How Can I Do This. Please help me.

**Comment by robustini** [comment]
@iskess: exactly!

**Comment by robustini** [comment]
I am proposing an option (selectable) of "takes pictures only inside the polygon", many who work with these aircraft are waiting for this option.

**Comment by meee1** [comment]
I should be able to add this, but the default will be off

**Comment by robustini** [comment]
Hi Michael, thanks!
Of course, the default will be off, but I'm sure the people who work with photomapping there will always put this option enabled.
I'm going to make a video of "APM:Plane V3.4.0" during a photogrammetry with auto takeoff and autolanding with my FX79, with triple visual (FPV, Planner and shoot), but before i wait this add-on.
Bests,

Marco

**Comment by robustini** [comment]
Feature "breakup starts" added, thanks @meee1!
