### ISSUE TITLE
AC3.3 changes some parameter names

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#810]
![paramchangesscreenshot](https://cloud.githubusercontent.com/assets/1498098/6520726/0640c766-c40e-11e4-97f8-97a82e39f0c3.png)

Old name                                  New Name                               Description
HLD_LAT_P                              POS_XY_P                              horizontal position controller
 
LOITER_LON_P                       VEL_XY_P                               horizontal velocity controller
LOITER_LON_I                         VEL_XY_I
LOITER_LON_IMAX                  VEL_XY_IMAX
LOITER_LON_D                       removed
                                                 VEL_XY_FILT_HZ                   input filter (new!)
 
THR_ALT_P                             POS_Z_P                               vertical position controller
 
THR_RATE_P                          VEL_Z_P                                vertical velocity controller
THR_RATE_I                           removed
THR_RATE_IMAX                    removed
THR_RATE_D                         removed
 
THR_ACCEL_P                       ACCEL_Z_P                             vertical acceleration controller
THR_ACCEL_I                        ACCEL_Z_I
THR_ACCEL_IMAX                 ACCEL_Z_IMAX
                                               ACCEL_Z_FILT_HZ                   input filter (new!)
 
LOITER_LAT_P, I, IMAX, D – removed because POS_XY_P is now a 2D pid controller
TRIM_THROTTLE – removed because it updates so quickly we can just set it to THR_MID at startup
POSCON_HOVER_THR – was a copy of TRIM_THROTTLE

**Comment by meee1** [comment]
9b9db01ed6aad9d15a63ac00aafb71b17401fc6c
