### ISSUE TITLE
Unable to upload a full mission's worth of waypoints 1.3.21 1.3.22

### ISSUE THREAD

**Issue by WickedShell** [diydrones/MissionPlanner#823]
Trying to upload a flight plan of 152 waypoints to the plane as far as mission planner is concerned it suceeded, however if you read back the waypoints it will have only succeeded in uploading between 60 and 100 waypoints. The dropped waypoints are scattered through out the mission, usually after 40 or so waypoints. 3DR radios were running SiK 1.9, most recent version of APM:Plane 3.2.3

The alarming aspect of this, is that it is a silent failure, and can leading to the plane navigating to unexpected locations.

The mission that didn't work is available here: http://pastebin.com/fJuetPLP

**Comment by meee1** [comment]
please provide the tlog

**Comment by WickedShell** [comment]
Sorry, the log can be found here: http://files.swiftradioplanes.com/2015-03-30%2016-26-26.tlog

**Comment by meee1** [comment]
looks like I have found this issue, 
the issue only occurs in heavy packet loss situations.
ie via usb is not an issue, via radio can be

**Comment by WickedShell** [comment]
1.3.23 fixed it, thanks!
