### ISSUE TITLE
Survey Grid: Mission Planner is not populating the takeoff angle

### ISSUE THREAD

**Issue by jmachuca77** [diydrones/MissionPlanner#825]
When doing a takeoff with a plane the takeoff angle must be added to the takeoff waypoint. Currently only the target altitude is populated but the angle is left as 0. This results in a dive to the ground right after a hand launch. Please add a takeoff angle of 20 deg

![screen shot 2015-04-01 at 9 32 07 am](https://cloud.githubusercontent.com/assets/1664405/6944758/ae77f8f2-d852-11e4-974a-7fa3f3ba5f8e.png)

Should be:
![screen shot 2015-04-01 at 9 36 50 am](https://cloud.githubusercontent.com/assets/1664405/6944764/b5d71826-d852-11e4-8a35-fd8127c3118d.png)

**Comment by meee1** [comment]
Jaime, I do have code to do this already, where you connected to the plane when you programmed the mission?

**Comment by jmachuca77** [comment]
No, I was not, and I did notice some of my missions do have it and some don’t. Is this only populated when you are connected to plane? Should it be always populated? I think copter will ignore it anyway right?

**Comment by jmachuca77** [comment]
So this does seem related to #826 after I connect to a plane and do a mission the pitch angle is correctly populated.

**Comment by meee1** [comment]
yes, correct
