### ISSUE TITLE
Flight Plan: Waypoint parameter descriptions for Takeoff missing

### ISSUE THREAD

**Issue by jmachuca77** [diydrones/MissionPlanner#826]
The waypoint description for takeoff angle is missing on the waypoint screen (first parameter "20" should read takeoff angle in description):

![screen shot 2015-04-01 at 9 36 50 am](https://cloud.githubusercontent.com/assets/1664405/6944796/ed1a1aea-d852-11e4-9b33-88254587e706.png)

**Comment by meee1** [comment]
this goes with #825, MP remembers the last device type you where connected to. and the last device time you where connected to was a copter, not a plane.

**Comment by jmachuca77** [comment]
Verified, after connecting to a plane the description appears correctly. Should this just stay the same on both plane and copter?

**Comment by meee1** [comment]
no, because there are several commands that differ, that's why they are like that.

if you click just under the baudrate selection box another drop down will appear, where you can override the current type
