### ISSUE TITLE
No line indicating waypoint flight path to lat/long 0,0

### ISSUE THREAD

**Issue by GenCodeInc** [diydrones/MissionPlanner#827]
When adding using the "Add New" button a waypoint is added in the Atlantic 0,0, problem is no line appears on map, if it is not noticed by the user or not changed to another command that does not use lat/long then a fly away will occur and in fact a fly away did happen to me but I was able to catch it and bring it home with RTL.

The default probably should not be waypoint 0,0, but more of a "Do nothing" command until the user selects a command, and if they do put in lat long 0,0 the line should not be hidden as it will truly try to fly there.

Thanks!

**Comment by meee1** [comment]
fix here https://github.com/diydrones/MissionPlanner/commit/e12f50b126f638977a196a3a063165c6c61054c3#commitcomment-10529514
