### ISSUE TITLE
Failed to Implement Mission Planner's HUD on my GCS

### ISSUE THREAD

**Issue by OpenGelo** [diydrones/MissionPlanner#828]
Hello,
I try to add hud.cs from MP's source code to my GCS. change old namespace to my namespace so that there is no error and i can implement it to my GCS. Next, I run it, and there is new item named HUD. Drag the HUD item to Main form, and run again. But I got this message box about null reference exception
 
![vsync failed](https://cloud.githubusercontent.com/assets/5819958/6963468/fbb759c4-d969-11e4-8a03-28bc5d673fcf.PNG)

what's wrong?  and how do I fix it? 
Thanks

**Comment by meee1** [comment]
it is a opengl issue, beyond that I cant tell you anything.
