### ISSUE TITLE
Feature Request: Plot ground station GPS and display distance from the aircraft to the ground station

### ISSUE THREAD

**Issue by WickedShell** [diydrones/MissionPlanner#832]
The hardware we use as a GCS has an internal compass that publishes a standard NMEA stream on a COM port, it would be really nice to be able to plot where the GCS currently is on the map, as well as the distance from the GCS to the last reported aircraft position.

I think most of the work is already covered with Follow Me mode, but I don't see a way to use Follow Me to plot the current GCS position.

**Comment by meee1** [comment]
give moving base a shot.
control-f > moving base

**Comment by WickedShell** [comment]
That sounds like what I'm looking for, although in testing it seems to crash everytime, since I can't copy paste the error I've attatched a screenshot of it. (sorry about the werid colors, they are selected for working well on a transflective screen in the sun)
![base](https://cloud.githubusercontent.com/assets/567688/6996384/d10d6f48-db39-11e4-83d7-e6170e4f6f1f.png)

**Comment by meee1** [comment]
2 options
user run as administrator.
or
on the link you use to start mp, set the working directory to the mp directory
