### ISSUE TITLE
Add support for DO_DIGICAM_* messages in mission planning screen

### ISSUE THREAD

**Issue by jmachuca77** [diydrones/MissionPlanner#841]
Currently only DO_DIGICAM_CONTROL (ID #203) mission items are supported, and there is no description of the fields. Please add the description of the fields and also add support for DO_DIGICAM_CONFIGURE (ID #202). 

DO_DIGICAM_CONFIGURE fields:
Mode | Shutter Speed | Aperture | ISO | ExposureMode | CommandID | Engine Cut-Off

DO_DIGICAM_CONTROL fields:
On/Off | Zoom Position | Zoom Step | Focus Lock | Shutter Cmd | CommandID

**Comment by rmackay9** [comment]
rock on
