### ISSUE TITLE
Live Calibration fails with unexpected error midway through calibration (reference to User hog?)

### ISSUE THREAD

**Issue by visser** [diydrones/MissionPlanner#849]
Hi diydrones, here's the exception details (summary and screenshot) and my config.xml, Windows 8.1, all updates with 3DR Pixhawk and NEO-6M gps+compass, MP: Mission Planner 1.3.25 build 1.1.5589.39444 (official)

![screenshot-mp2](https://cloud.githubusercontent.com/assets/1157602/7332832/3c75b030-eb55-11e4-815e-f22411cce7b6.jpg)
![screenshot-mp1](https://cloud.githubusercontent.com/assets/1157602/7332833/3c791004-eb55-11e4-8325-83fd2f47b249.jpg)

Object reference not set to an instance of an object.

at MissionPlanner.MagCalib.prd_DoWork(Object sender, ProgressWorkerEventArgs e, Object passdata) in C:\Users\hog\Documents\Visual Studio 2010\Projects\ArudpilotMega\ArdupilotMega\MagCalib.cs:line 400

**Comment by visser** [comment]
Re-installed Mission Planner from the Help screen and was able to complete calibration :)

**Comment by meee1** [comment]
one question, how did you install mp in the first instance? zip? msi? etc,

**Comment by visser** [comment]
Always via MSI installed and once installed then using the auto updater
within MP :)
