### ISSUE TITLE
Tracker: show tracker's desired and actual heading with red/orange line

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#852]
![tracker_redorangelines](https://cloud.githubusercontent.com/assets/1498098/7340591/d0ed832e-eccb-11e4-86fd-d5c5661c2f8a.png)
It would be nice if the red and orange lines on the MP were updated with the Tracker's actual and desired heading.  The tracker software is sending these values down in the nav-output message.

**Comment by meee1** [comment]
https://github.com/diydrones/MissionPlanner/commit/a183c3d6ce2d62050ecf1e9d705a9239b60e4ba0
and
https://github.com/diydrones/MissionPlanner/commit/b0f5675a91dbb24386d91ede634f92355da2c728

**Comment by rmackay9** [comment]
thanks very much!
