### ISSUE TITLE
Feature Request: Select multiple .bin  files for conversion to .log simultaneously

### ISSUE THREAD

**Issue by nicksargeant** [diydrones/MissionPlanner#854]
Minor enhancement: please allow the selection of multiple .bin files for conversion in the "DataFlash Logs" tab of MP (as is possible when converting dataflash logs to KML + gpx files).
Thanks!

**Comment by nicksargeant** [comment]
Hi Michael. 
Thank you for adding this functionality! Minor additional request; Is it possible for the text logs to be generated in the same directory as the source .bin files rather than in C:\Program Files (x86)\Mission Planner?

**Comment by meee1** [comment]
i would say that's an oversight on my part :)
