### ISSUE TITLE
Geo Ref tool CAM message validation

### ISSUE THREAD

**Issue by nicksargeant** [diydrones/MissionPlanner#856]
Minor enhancement: While the CAM message syncro should either work or fail with a warning, I would find it useful for the log window to display the calculated offset time for a means of validation as shown:
![georef](https://cloud.githubusercontent.com/assets/5547169/7385594/91cdd2aa-ee7b-11e4-84d0-f8621f86c963.png)
As they should all return the same value, being able to quickly view the actual time offset allows easier verification that georeferencing has worked successfully over multiple flights that have to be individually georeferenced.
Thank you as awlays!

**Comment by meee1** [comment]
could you provide an example? just so I fully understand what you are requesting?
we have the cam message time, and we will have the image time, is that what you want? the delta time?

**Comment by nicksargeant** [comment]
Sorry Michael, my request wasn't particularly clear. As you discerned, all i would like the tool to do is somewhere display the delta time calculated when using the CAM message to georeference images.
