### ISSUE TITLE
Feature Request: Tracker - Enable setting tracking location to be static.

### ISSUE THREAD

**Issue by ryanjohnston4** [diydrones/MissionPlanner#858]
It would be great if we could set the location static of where the antenna will point and track, i.e. the home location and have the antenna tracker not need anything but GPS and the predefined location from its initial power on. Then no telemetry/mavlink connection is needed and the tracker can be used in the air with its sensors to point an antenna to the specific location on the ground.

**Comment by meee1** [comment]
do you mean for the internal mp tracking? or the hardware based antenna tracker?

**Comment by ryanjohnston4** [comment]
The hardware based antenna tracker - to have an antenna point back to the home or set location from the air.

**Comment by meee1** [comment]
ok, so its not the hardware tracker at all?
your talking about using a gymbal on a plane to point at home?

**Comment by ryanjohnston4** [comment]
I mean loading up the antenna tracker firmware on a separate onboard APM (independent of the flight controller unit) and using it on a small gimbal to point the antenna home. Directional antennas in 5.8 spectrum are so small with high gain; would be extremely beneficial for link quality.

**Comment by rmackay9** [comment]
Ok so this request probably belong in the ardupilot issues list then.  You want to add it there?
https://github.com/diydrones/ardupilot/issues

I've been thinking of adding this to the antenna tracker firmware actually.

**Comment by ryanjohnston4** [comment]
Thanks will do now.   

Would be a really great function!
