### ISSUE TITLE
Optional Hardware: add support for a second battery monitor

### ISSUE THREAD

**Issue by taedla01** [diydrones/MissionPlanner#859]
Hello everyone,
Now that Arduplane and Arducopter code supports the use of a second battery monitor through the Pixhawk ADC ports, would be great to configure it like the main battery monitor, i.e, through the optional hardware tab instead of the full parameter list.

Thanks for your time and your effort,
Regards from Spain,
Dario.

**Comment by proficnc** [comment]
+1 pixhawk 2 will have capability for 2 power modules, so it would be great to be able to display the second battery.

**Comment by lvale** [comment]
+1 Second that

**Comment by taedla01** [comment]
Hello everyone,

This issue has been solved since Mission Planner 1.3.33 has been released so I close the issue. Take a look at the Pixhawk pinout adc references for know more about the second battery monitor implementation.

Cheers,
Dario.

**Comment by lvale** [comment]
Although it can be configured on the PixHawk, unless you add the fields manually there is no feedback. Case of the HUD, the rede letters I assume are Batt1 only.

<img width="654" alt="screen shot 2016-02-17 at 14 34 00" src="https://cloud.githubusercontent.com/assets/3130363/13112755/21947d2c-d584-11e5-8fb7-c9293554b8bf.png">


<img width="649" alt="screen shot 2016-02-17 at 14 34 52" src="https://cloud.githubusercontent.com/assets/3130363/13112759/29d2a392-d584-11e5-8164-a78bf7a9c854.png">


<img width="494" alt="screen shot 2016-02-17 at 14 32 21" src="https://cloud.githubusercontent.com/assets/3130363/13112768/366898aa-d584-11e5-936e-5a1d812077ef.png">
