### ISSUE TITLE
Beta Firmware descriptions incorrect on Install Firmware page

### ISSUE THREAD

**Issue by ggregory8** [diydrones/MissionPlanner#865]
When selecting the 'Beta firmwares' link on the Install Firmware page it retrieves the FW list/versions and changes the descriptions, but they are incorrect and showing V3.2 instead of V3.3-rc3, at least for AC. You can see this and the MP version in the screenshot below. Running on Win8 x64.

I can confirm by selecting 'ArduCopter V3.2 Quad' it does intall AC3.3-rc3.

![beta_firmware_descriptions](https://cloud.githubusercontent.com/assets/5005893/7557441/1ea1e440-f7c4-11e4-9ad3-4aabed310336.png)

**Comment by meee1** [comment]
I just tested, and it worked fine. please try it again.

**Comment by ggregory8** [comment]
Still the same issue. I noticed this on the older version on MP as well. Maybe it is something specific to my setup.

As mentioned it is only the descriptions that are wrong. It still loads AC3.3-rc3

**Comment by meee1** [comment]
please upload your missionplanner.log

**Comment by meee1** [comment]
and do you use a proxy server?

**Comment by ggregory8** [comment]
Log found here. Last thing I done was opened MP. Went to install firmware page, then clicked beta firmware and ok on prompt box. Then closed.
https://drive.google.com/file/d/0B2tRJoqjaZmxQi1GaHk2ZGp5M28/view?usp=sharing

No proxy.

**Comment by meee1** [comment]
please update your mission planner version!!
the firmware version its looking up for for the apm2, which is no longer supported, and explans the older version label

**Comment by ggregory8** [comment]
Sorry I thought I was running the latest version of MP as it normally asks to update if not. Just discovered the update option in Help tab.
Thanks that has fixed it.
