### ISSUE TITLE
Dataflash log screen not showing ATDE, ATUN messages in drop-down on right

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#869]
![missingatde-atun](https://cloud.githubusercontent.com/assets/1498098/7603003/26c823b0-f967-11e4-8ffd-b3182ed7f82d.png)

Dataflash log is here: https://dl.dropboxusercontent.com/u/3852647/Randy-MP-DF-missingATUN/2015-05-05%2018-51-54.bin

**Comment by meee1** [comment]
mp was looking for messages within the first 30000 lines only, i will modify to look through the first 60000 lines

**Comment by meee1** [comment]
https://github.com/diydrones/MissionPlanner/commit/f873a7dcca042fda2367b2a9454c00d65d94a069

**Comment by rmackay9** [comment]
thanks!
