### ISSUE TITLE
TradHeli Rate FF not operational in Extended Tuning

### ISSUE THREAD

**Issue by R-Lefebvre** [diydrones/MissionPlanner#876]
On the Extended Tuning page, when connected to a TradHeli, the Rate Roll FF and Rate Pitch FF parameter blocks are greyed out and not usable.

![mp tradheli rate ff problem](https://cloud.githubusercontent.com/assets/3228111/7756640/9816f640-ffca-11e4-87b2-fb01ca3e375c.png)

**Comment by meee1** [comment]
rob, whats the name of the param?
it used to be RATE_ROLL_FF and RATE_PITCH_FF

**Comment by R-Lefebvre** [comment]
Ah, that's why.  I'm not sure when/why it changed, but now its:

RATE_PIT_FF
RATE_RLL_FF

**Comment by meee1** [comment]
done
