### ISSUE TITLE
Standardize Measurement Displays/Outputs

### ISSUE THREAD

**Issue by dcwalmsley** [diydrones/MissionPlanner#878]
Recently I installed a LiDAR unit and configured the "Quick" Tab on Mission Planner to show me Alt and Sonar Range.  Since I set my configuration in the setup section for Speed in MPH and Distance in Feet, I noticed the Alt is correctly show Feet for its altitude but Sonar Range reads in Meters.

Request that all output readouts reflect the same measurement values as defined by operator in the configuration section of the mission planner.

**Comment by meee1** [comment]
done
