### ISSUE TITLE
Error EKF PRED POS HORIZON

### ISSUE THREAD

**Issue by Jman841** [diydrones/MissionPlanner#880]
I am receiving this error message with both Arduplane 3.3.0 and Arducopter ever since updating to 1.3.27

"Error EKF PRED POS HORIZON"

**Comment by BruceParmele** [comment]
I am having the same issue.

**Comment by meee1** [comment]
do you have a stable gps lock when it displayed it?

**Comment by Jman841** [comment]
Yes. It is displayed the entire flight and GPS HDOP is around 1.2. It happens on both arducopter and arduplane 3.3 with different vehicles.

**Comment by meee1** [comment]
this should now be resolved with 1.3.28
