### ISSUE TITLE
Data Flashlog Autoanalysis dont work

### ISSUE THREAD

**Issue by chuti** [diydrones/MissionPlanner#881]
If I want to open a logfile, then I get the errormessage "global name 'sqrt' is not defined", "Bad input file".
If I want to open the logfile with "Review a log" it works, but the values of the function "Show Pointvalue" are always wrong.

**Comment by KD2DEY** [comment]
I have had the same experience with 1.3.27 (build 1.1.5620.38044). Reverting to an earlier version of MP resolves the issue so it's clearly an issue with this version of MP.

**Comment by meee1** [comment]
this should now be resolved with 1.3.28
