### ISSUE TITLE
If RCMAP is used, radio calibration screen saves min/max to wrong channel

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#883]
MP is correctly displaying the moving green bars on the radio calibration page but the display of the red min/max lines is incorrectly mapped.  the saving of the actual RCX_MIN/MAX values seems correct however.
In the example below channels 2 and 3 were swapped using RCMAP.  The red lines were displayed incorrectly and the RC2_MIN/MAX values were also incorrectly saved with RC3_MIN/MAX
![mp_rcmap1](https://cloud.githubusercontent.com/assets/1498098/7796977/b71ad58a-0320-11e5-87fa-09c23366d6d3.png)

**Comment by meee1** [comment]
i believe this is fixed

**Comment by andyp1per** [comment]
Worked for me
