### ISSUE TITLE
radio calibration screen not using RCMAP first time it's opened

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#884]
To reproduce the issue switch around two channels (i.e. RCMAP_PITCH =3, RCMAP_THROTTLE = 2).
Start the MP and connect to Pixhawk running AC3.3-rc5 (or whatever).  Go to the radio calibration screen and note the green bars move as if the RCMAP changes had not been done.
Click to Config/Tuning and then back to Radio Calibratoin and note that the green bars have now moved correctly taking the RCMAP into account.
![mp_rcmap_1sttimewrong](https://cloud.githubusercontent.com/assets/1498098/7797228/2ddc76e4-0324-11e5-9736-c0070be9c42c.png)

**Comment by meee1** [comment]
i believe this is fixed

**Comment by andyp1per** [comment]
Worked for me when I just tried it with .28
