### ISSUE TITLE
Date of release in the changelog.txt

### ISSUE THREAD

**Issue by jmacgithu** [diydrones/MissionPlanner#885]
It is a trivial request, but would it be possible to add the date of release in the changelog.txt, at least for the future releases?
I'm working with ardupilod master and sometimes I don't use MP for days. When I download a new release, I can't determine when it was released and wheter some of the latest features of ardupilot were included or not. Of course I could read the whole changelog.txt, but it would be faster to compare a ardupilot commit date and MP release and it'd be faster.
Thanks
Fabio

**Comment by meee1** [comment]
i wil ltry to keep this happening on new releases
