### ISSUE TITLE
Moving waypoints all at once

### ISSUE THREAD

**Issue by rdesgagn** [diydrones/MissionPlanner#892]
Sometimes when I plan a mission, I would like to be able to move all the waypoints at once so I don't have to move each of them separately. I don't know if other users already asked for this feature but I think it would increase efficiency at creating mission.

It could be done by right clicking on one of the leg between two waypoints for example and while holding down the mouse button, drag to where you want the new waypoint(s).

**Comment by meee1** [comment]
hold down control, and try.

**Comment by meee1** [comment]
work?

**Comment by rdesgagn** [comment]
Yes, it works. Thanks a lot Michael.

Le dim. 14 juin 2015 à 19:53, Michael Oborne <notifications@github.com> a
écrit :

**Comment by reluctantgithubuser** [comment]
Hi-
Did the control select feature get removed?
I cannot select multiple waypoints with control drag.
I can draw the blue box around the waypoints but nothing I click allows me to move all of them.
It just moves one waypoint or adds another if I left click inside the blue box.
Win8 pc, MP 1.3.58
