### ISSUE TITLE
AUTO mode no longer works for connect

### ISSUE THREAD

**Issue by andyp1per** [diydrones/MissionPlanner#894]
I get an error when connecting as shown below.
![new picture 2](https://cloud.githubusercontent.com/assets/2893260/7971591/c9cb0fdc-0a3d-11e5-83e1-b88761d43232.jpg)
I also get an error if I try and use COM3 directly. The only way I can reliably connect is by first using AUTO, have that fail and then try connecting again using the default displayed.
This is with MP 1.3.28

**Comment by meee1** [comment]
fixed here
https://github.com/diydrones/MissionPlanner/commit/177c5375eeeb1e0401296a6f7783b804dd8cb1a2
