### ISSUE TITLE
Radio calibration, min max UI issue

### ISSUE THREAD

**Issue by github-0** [diydrones/MissionPlanner#896]
When doing the radio calibration today, I noticed the UI mixes throttle and yaw min/max red marks with each other. The dialog showing saved values is correct, so probably just a UI issue.

Tried to uninstall and reinstall MP, no change (the MP folder under program files didn't get removed when I used the uninstall wizard, so I deleted it manually). MP version 1.3.28, plane version 3.3.0.

![mp_calibration_problem](https://cloud.githubusercontent.com/assets/6333614/8025372/c5fa9ff4-0d5c-11e5-848a-1db68b5eebe4.png)

**Comment by andrea25** [comment]
Similar Issues here.
Look at my screenshot.

![calibrationproblem1](https://cloud.githubusercontent.com/assets/10176752/8025602/fafc1d14-0d5b-11e5-88cb-da7b62e1c43e.jpg)

![calibrationproblem2](https://cloud.githubusercontent.com/assets/10176752/8025604/02adfe06-0d5c-11e5-8348-55e64121293e.jpg)

**Comment by meee1** [comment]
this has been resolved in the current beta already. it is just a gui bug
https://github.com/diydrones/MissionPlanner/issues/883
