### ISSUE TITLE
Latest beta unable to perform update

### ISSUE THREAD

**Issue by lvale** [diydrones/MissionPlanner#908]
Several errors while copying files.

I have enable betas selected. Standard installation on Windows 7 -64

![screen shot 2015-06-19 at 23 49 01](https://cloud.githubusercontent.com/assets/3130363/8264768/6e85195e-16e2-11e5-824d-dc869df5dfed.png)
![screen shot 2015-06-19 at 23 48 27](https://cloud.githubusercontent.com/assets/3130363/8264769/6ea9a990-16e2-11e5-8aba-3384712f71d9.png)

**Comment by meee1** [comment]
please check missionplanner is not still running, ie in task manager. then retry.

**Comment by lvale** [comment]
did that, and no it wasn't running

**Comment by meee1** [comment]
the only reason it can fail is either file permissions, or the file is in use.
could be MP, antivirus, etc, etc

**Comment by lvale** [comment]
Repeated the upgrades cycle and I believe it could have been a beta over beta issue, or networking snafu.....
![screen shot 2015-06-30 at 23 27 55](https://cloud.githubusercontent.com/assets/3130363/8445984/ef1809fc-1f9b-11e5-9d4c-a8e1a9646842.png)
