### ISSUE TITLE
Add support for nsh terminal over mavlink

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#916]
Tridge has recently added support for accessing the nsh terminal over MAVLink.  This was primarily for Solo which doesn't provide any access to the serial4/5 port on the PH2 but it would be useful for other developers who don't want to mess around trying to create a Debug Cable.
http://dev.ardupilot.com/wiki/apmpilot_project_developer_information/interfacing-with-pixhawk-using-the-nsh/

Details of how to do the setup with MAVProxy are at the bottom of the page above.  Tridge can probably provide details of the MAVLink messages to use to accomplish this.

**Comment by meee1** [comment]
already done.
terminal > select nsh from the dropdown.
dont do it while in the air atm.....

**Comment by meee1** [comment]
cf6afcbf421ae19a06e3634ed6c2d2263b0d3c8f

**Comment by rmackay9** [comment]
ah, very cool.
