### ISSUE TITLE
Mission Planner using windows XP / Not showing flight modes

### ISSUE THREAD

**Issue by dudz996** [diydrones/MissionPlanner#958]
I have seen this issue all over the net, but no evidence of cures.

I have been Using versions of MP up until 2014 with great success along with my APM2.0 board.
I updated MP to the latest version, and loaded the latest possible firmware. Now, using my Turnigy 9x radio, on the MP Modes screen , I switch the radio to all my usual modes but MP does not show any modes, just blank tabs. Plus near the top of MP states "unknown". I have tried to load previous firmwares and MP versions, but it makes no difference. I just received a AMP2.6 clone, and it acts exactly the same with MP.  I am not using an OSD with the AMP so I don't know if the modes are showing there either.
![modes](https://cloud.githubusercontent.com/assets/6160168/9074110/0596e14a-3b07-11e5-8ca6-540c79fbbda6.JPG)

**Comment by meee1** [comment]
please do an update, on the help screen. this will redownload that missing file

**Comment by Juemo** [comment]
Same probleme here with win XP for past week.
I have deinstall the MP and then I have use CCleaner tool for clean the Windows Registry
Then the new last MP installation works now ok here.

**Comment by dudz996** [comment]
When I started MP thismorning, a new update automatically installed. This has indeed cured it. Thankyou !


  ----- Original Message -----

**Comment by dudz996** [comment]
When I started MP this morning, a new update automatically installed. This has indeed cured it. Thankyou !
