### ISSUE TITLE
float to double problem in params

### ISSUE THREAD

**Issue by magicrub** [diydrones/MissionPlanner#963]
params are transferred in float via MAVLink, but appear to be converted to doubles internally now. This happened from going tom 1.3.30 to 1.3.31. No big deal until you start interacting with param files.

Example: My file has EKF_VELD_NOISE,0.7 and EKF_WIND_PNOISE,0.1
When I go to compare to current settings I get
EKF_VELD_PNOISE (value) 0.699999988079071   (new) 0.7
EKF_WIND_PNOISE (value)  0.100000001490116   (new) 0.1

**Comment by meee1** [comment]
agh yes, I fixed the log file saving/loading. just not the param compare

**Comment by magicrub** [comment]
I see you've made a commit, is this fixed now? I can use beta but it's driving my team nuts. Can we push out a release soon?

**Comment by magicrub** [comment]
fixed in the beta, thank you!
