### ISSUE TITLE
when RTSCTS enabled , no connection on 1.3.31 , but connects on 1.3.10

### ISSUE THREAD

**Issue by itayguy** [diydrones/MissionPlanner#967]
I added print screen of the radio config.

![connects with both](https://cloud.githubusercontent.com/assets/4155188/9268952/da7734b6-426c-11e5-8d49-23ec575ce871.png)
![connects only with 1 3 10](https://cloud.githubusercontent.com/assets/4155188/9268953/da7a01e6-426c-11e5-9ec1-674a58cbb497.png)

**Comment by meee1** [comment]
are you sure this is not as issue with the AP?
is the only change you are making a MP version?

**Comment by itayguy** [comment]
yes,
but I must say I cannot replicate it now !#@
