### ISSUE TITLE
NTUN doesn't appear in right-side expander

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#972]
![ntunmissingfromrightsideexpanded](https://cloud.githubusercontent.com/assets/1498098/9295865/957acdda-44b7-11e5-8bf9-1c4d6f9c6aa6.png)

I think the issue is probalby not that it's NTUN specifically but perhaps it doesn't appear for some time in the logs or something.
Here's a link to the log: https://dl.dropboxusercontent.com/u/3852647/MP_missingNTUN/2015-08-16%2017-00-00-batt18650BD.BIN

**Comment by meee1** [comment]
this will be because the first ntun message is over 500000 lines into the file.
from your SS it is 666795, I will increase this limit

**Comment by rmackay9** [comment]
ok, thanks a lot!
