### ISSUE TITLE
GeoRef Tool: Time offset calculation using CAM messages broken

### ISSUE THREAD

**Issue by jmachuca77** [diydrones/MissionPlanner#973]
When trying to get the time offset estimation using the CAM Messages GPS location and the first pictures, the GeoRef Tool crashes.
<img width="1134" alt="screen shot 2015-08-16 at 9 29 11 pm" src="https://cloud.githubusercontent.com/assets/1664405/9297011/fd78b866-445d-11e5-963f-a5657d65c97e.png">

**Comment by meee1** [comment]
changes made in 1.3.32 to use fmt message.
