### ISSUE TITLE
text message severity change

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#977]
For future releases of Copter, Tracker, Plane, Rover the severities of text messages sent from the flight controller will change to be consistent with the MAVLink standards.

Before                            After
SEVERITY_LOW =1       MAV_SEVERITY_WARNING = 4
SEVERITY_MEDIUM =2  MAV_SEVERITY_ALERT =1
SEVERITY_HIGH =3       MAV_SEVERITY_CRITICAL =2

During the transitional period in which the GCSs want to support firmware which could send either set of severities, the autopilot version could be used (http://mavlink.org/messages/common#AUTOPILOT_VERSION).  The first version to support the new severities is below.
Copter: 3, 4, 0, FIRMWARE_VERSION_TYPE_DEV
Plane: 3,4,0,FIRMWARE_VERSION_TYPE_BETA
Rover: 2, 6, 0, FIRMWARE_VERSION_TYPE_DEV
Tracker: 0, 7, 3, FIRMWARE_VERSION_TYPE_DEV

**Comment by meee1** [comment]
done 
https://github.com/diydrones/MissionPlanner/commit/78f11d589dca1d721e74045030b0f381d2ae513c
