### ISSUE TITLE
Mission Planner crashes with Log files

### ISSUE THREAD

**Issue by lvale** [diydrones/MissionPlanner#979]
While attempting to load a log file (120+ Mbytes )

![untitled](https://cloud.githubusercontent.com/assets/3130363/9537510/1a991586-4d31-11e5-84e1-31cb0d2a123b.png)

Michael, if you want I can give you access to the original BIN files.

btw: it was impossible to retrieve the logs via the Mavlink interface, so I had to eject the card and copy the logs directly to the computer.

**Comment by meee1** [comment]
are you sure the log you picked wasn't a blank file?

**Comment by lvale** [comment]
Sure, even had Peter Barker confirm one of the files for me with MavTools

**Comment by meee1** [comment]
I tested with a 800mb bin file and didn't have any issues. does mp do it everytime? do you have enough free disk space?

**Comment by lvale** [comment]
400GB+ of disk free space. MP does it everytime. I'm on Mumble and send you the Google drive link to 4 recent logs that all do the same, 1.bin 2.bin 3.bin 4.bin each about 120MB each

**Comment by meee1** [comment]
can you try the latest beta? as I cant reproduce

**Comment by lvale** [comment]
Same issue with latest beta. Even on 10Mb Bin file, so it might not be related to file size but with some parameter

**Comment by lvale** [comment]
Well. It turns out that Copter RC9 saved 130MB blank log files.....So not a MP issue.
