### ISSUE TITLE
Mission Planner latest update errors

### ISSUE THREAD

**Issue by lvale** [diydrones/MissionPlanner#980]
Today, MP pop'd up the new beta available and I accepted the offer to upgrade. 

Screenshot is part of the dialog that ends with, unable to upgrade. Tested on 2 different machines both with Windows 7 - 64

<img width="669" alt="screen shot 2015-08-29 at 20 53 48" src="https://cloud.githubusercontent.com/assets/3130363/9564092/a9da2a66-4e92-11e5-98e6-82c6d7e83900.png">

**Comment by meee1** [comment]
restart windows, explorer.exe has that file locked. I see this one fairly often

**Comment by lvale** [comment]
Probably not
2 attempts, same result, both from fresh booted windows.
https://youtu.be/Ql9WXL3RQO4

**Comment by meee1** [comment]
do you have tlogs on your desktop?

**Comment by lvale** [comment]
Those tlogs are from Tower that I copied to the desktop. Unrelated issue.

**Comment by meee1** [comment]
in this case they are related.
the tlog thumbnail driver will be trying to create thumbnails for them. and explorer.exe will be locking the dll because of it
