### ISSUE TITLE
Set Mount button / dropdown not working

### ISSUE THREAD

**Issue by fillycheezstake** [diydrones/MissionPlanner#981]
It would appear that recent changes to ardupilot / the parametermetadata.xml has broken this functionality. The parameter MNT_MODE isn't in the xml or online documentation for the parameters.

In FlightData.cs, there's a line of code to put the list of available mount modes into the drop-down menu -

CMB_mountmode.DataSource = ParameterMetaDataRepository.GetParameterOptionsInt("MNT_MODE", MainV2.comPort.MAV.cs.firmware.ToString());

This MNT_MODE parameter no longer exists? Is this depreciated? How do we change the mount mode now?  I was trying to make myself a 'Camera Control' tab in the FlightData screen, and as of now, the only way I can change the mount mode is via the transmitter. 

Thanks - should I post something on the drones-discuss group as well? (it's possible I'm just missing something stupid, but that MNT_MODE parameter is missing on the ardupilot documentation as well.)

**Comment by rmackay9** [comment]
@fillycheezstake, it's been renamed to MNT_DEFLT_MODE.  It's best not to try and control the vehicle (or mount) by directly setting parameters.   Instead the do-mount-control or do-mount-configure mavlink messages should be used. Becareful, there's duplicates of these messages, the originals that appear in ardupilotmega.xml and then the newer version in common.xml which are meant to be sent as MAV_CMD within a command-long or mission-item.  It's better to use the common.xml version.

Note that there's an outstanding PR for copter that ensures that the common.xml version is implemented (Copter may currently only implement the ardupilotmega.xml version)
