### ISSUE TITLE
Failed to update home location when SToRM32 gimbal is attached using MAVLink protocol

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#986]
When using Copter-3.3 with a SToRM32 gimbal and the MAVLink protocol, soon after connecting and at the end of downloading parametes (from perhaps both the vehicle and the gimbal) a "Failed to update home location" message is displayed to the user.
My guess is that Mission Planner is either trying to retrieve or perhaps set the gimbal's home location which is not possible and this message appears.
At the time this happens the vehicle selector box is also on the screen but the user can't modify it because the parameter download is ongoing with a modal window.

**Comment by meee1** [comment]
do you have arming turned off?

**Comment by rmackay9** [comment]
@meee1, Actually it's not possible to disable arming in copter.  the ARMING_CHECK parameter is also "1" in case that's what you meant.
