### ISSUE TITLE
FlightPlan: DO_MOUNT_CONTROL column headers missing

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#988]
The titles are:
Param1: Pitch
Param2: Roll
Param3: Yaw

![mp_domountcontroltitles](https://cloud.githubusercontent.com/assets/1498098/9703002/94621432-54af-11e5-8fe2-d7ec3bd20075.png)

Ideally we should get these in for the Copter-3.3 release although it's not super urgent really.

**Comment by meee1** [comment]
are these copter only? or all platforms?

**Comment by rmackay9** [comment]
@meee1, all platforms.

**Comment by meee1** [comment]
done

**Comment by rmackay9** [comment]
thanks so much!
