### ISSUE TITLE
Full Parameter List - Changes to values causes a crash of Mission Planner

### ISSUE THREAD

**Issue by bionicbone** [diydrones/MissionPlanner#991]
If you open the full parameter list in v1.3.31 and change any value, when pressing enter mission planner crashes.

Was OK in v1.3.30

Using v3.2.1 APM copter on Pixhawk.

Tested by myself and one other user over on RCGroups, both same version and firmware.

Kev

**Comment by meee1** [comment]
please provide a log/video. as this cant be a widespread problem.

**Comment by bionicbone** [comment]
Hi Michael,

I've done a video, its available here.
https://www.youtube.com/watch?v=Q3H9JcyoivU&feature=youtu.be

Kev

**Comment by meee1** [comment]
can you tell me what version of Microsoft .net you have installed. I have a feeling it will be something to do with the software installed on your pc.

**Comment by bionicbone** [comment]
I have everything from 2 upwards I think, with the most recent being v4.5.51209

![image001](https://cloud.githubusercontent.com/assets/7845867/9734245/5cb62584-5629-11e5-9614-76b66079e527.png)
![image002](https://cloud.githubusercontent.com/assets/7845867/9734246/60af7b68-5629-11e5-8971-bc0be75f512b.png)

I'll try installing on a different laptop that is a base Win 7

Kev

**Comment by bionicbone** [comment]
Hi Michael,

You were correct, it must be a local issue on my laptop as installing V1.3.31 on another laptop, connecting to the same UAV does not have the same problem as I experiance on the original laptop.

Clearly, I'm not the only person to have the trouble as it was mentioned on RCGroups, but also it's not wide spread either othe rise you'd have loads of reports by now.

When I can I will run the VS debugger to see if I can track down the issue, for now I will have to live with it.

Kev

**Comment by meee1** [comment]
the problem from what I can see its crashing in the system.windows.forms library, which is a system library, I can only suggest reinstalling the .net framework, V4. and see if this resolves it.

**Comment by bionicbone** [comment]
That's easy fixed, I'll  reinstall .net v4 later today.

**Comment by bionicbone** [comment]
Hi Michael,

I just downloaded v1.3.32 and the problem seems to be resolved.

This other user also reported the issues being resolved with this release.

http://www.rcgroups.com/forums/showpost.php?p=32698819&postcount=6223

For info I did also install windows 10 so that may have helped or it could have been something you updated.

I'm closing the issue.

Thanks
Kev
