### ISSUE TITLE
negative altitude possible in a survey ?

### ISSUE THREAD

**Issue by arnaudstephan** [diydrones/MissionPlanner#994]
Hi !

Is it possible to add a WP with a negative altitude (ie : -10 m) ?

For exemple : i start a survey with a copter and i want to maintain always same altitude between copter and land. If a decide to fly at 50 m but a part of the land is below 50 m.

See the picture, it's easier to understand : 
![text5040-6](https://cloud.githubusercontent.com/assets/11520915/9773001/0510d230-5740-11e5-8dad-6f44c1a0f8fc.png)
Thank you.

**Comment by rmackay9** [comment]
ardupilot can handle negative altitudes so I think it will work.

**Comment by arnaudstephan** [comment]
Thank you Randy
