### ISSUE TITLE
Warnings from MP without vehicle powered

### ISSUE THREAD

**Issue by lvale** [diydrones/MissionPlanner#996]
MP keeps saying the audio warnings selected (like voltage) even when the vehicle battery is disconnected and the radio link lost. On this TLOG I change batteries on the quad several times and while I'm switching batteries the voltage warning keeps sending notifications, with the vehicle without battery....

Shouldn't it notify Vehicle link lost ??

the TLOG
https://drive.google.com/open?id=0BzRxu4IwHPYCcDJiMGdMVHZtQ1U

Copter 3.3RC11 and latest MP Beta.

**Comment by meee1** [comment]
was the mav armed? if it was disarmed, then it worked as desired.

 if ((DateTime.Now - MainV2.comPort.MAV.lastvalidpacket).TotalSeconds > 10
                        && (DateTime.Now - connecttime).TotalSeconds > 30
                        && (DateTime.Now - nodatawarning).TotalSeconds > 5
                        && (MainV2.comPort.logreadmode || comPort.BaseStream.IsOpen)
                        && MainV2.comPort.MAV.cs.armed)
